# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgetoken',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do token. Ex: {"device": "iPhone 15", "login_source": "whatsapp"}', verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='identitylink',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do vínculo. Ex: {"device": "Chrome/120", "ip": "192.168.1.1"}', verbose_name='metadados'),
        ),
    ]
