# Generated by Django 5.2.11 on 2026-04-20 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerman', '0004_alter_product_sku'),
        ('orderman', '0002_alter_sessionitem_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação')], max_length=50, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('order_ref', models.CharField(blank=True, max_length=50, verbose_name='ref do pedido')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='reconhecido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'alerta operacional',
                'verbose_name_plural': 'alertas operacionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_amount_q', models.IntegerField(default=0, help_text='Valor de abertura em centavos (fundo de troco).')),
                ('closing_amount_q', models.IntegerField(blank=True, help_text='Valor informado no fechamento em centavos.', null=True)),
                ('expected_amount_q', models.IntegerField(blank=True, help_text='Calculado: abertura + vendas_dinheiro + suprimentos - sangrias.', null=True)),
                ('difference_q', models.IntegerField(blank=True, help_text='Diferença: fechamento informado - esperado (positivo = sobra).', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-opened_at'],
                'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)')],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('amount_q', models.IntegerField(help_text='Valor em centavos (sempre positivo).')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='backstage.cashregistersession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('data', models.JSONField(blank=True, default=list, help_text='Snapshot de fechamento do dia. Schema definido pela instância.', verbose_name='snapshot')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento do dia',
                'verbose_name_plural': 'fechamentos do dia',
                'ordering': ['-date'],
                'permissions': [('perform_closing', 'Pode executar fechamento do dia')],
            },
        ),
        migrations.CreateModel(
            name='KDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('prep', 'Preparo'), ('picking', 'Separação'), ('expedition', 'Expedição')], max_length=20, verbose_name='tipo')),
                ('target_time_minutes', models.PositiveIntegerField(default=10, help_text='Timer fica amarelo após este tempo, vermelho após 2x.', verbose_name='tempo alvo (min)')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='som ativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('config', models.JSONField(blank=True, default=dict, help_text='text_size, dark_mode, refresh_interval, etc.', verbose_name='configurações')),
                ('collections', models.ManyToManyField(blank=True, help_text='Categorias de produto que esta estação processa. Vazio = catch-all.', to='offerman.collection', verbose_name='coleções')),
            ],
            options={
                'verbose_name': 'instância KDS',
                'verbose_name_plural': 'instâncias KDS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='[{"sku", "name", "qty", "notes", "checked": false}]', verbose_name='items')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluído')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('kds_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='backstage.kdsinstance', verbose_name='estação KDS')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='orderman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'ticket KDS',
                'verbose_name_plural': 'tickets KDS',
                'ordering': ['created_at'],
                'permissions': [('operate_kds', 'Pode operar telas KDS (check, done, expedition)')],
            },
        ),
    ]
