# Generated by Codex on 2026-05-04

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0004_production_reports_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSTab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Código armazenado com 8 dígitos. Ex: 00001007.",
                        max_length=8,
                        unique=True,
                        validators=[RegexValidator("^\\d{8}$", "Use exatamente 8 dígitos.")],
                        verbose_name="código",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=64, verbose_name="rótulo")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
            ],
            options={
                "verbose_name": "POS tab",
                "verbose_name_plural": "POS tabs",
                "ordering": ["code"],
            },
        ),
    ]
