# Generated by Django 6.0.5 on 2026-05-06 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_alter_operatoralert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição curta')),
                ('moment', models.CharField(choices=[('opening', 'Abertura'), ('routine', 'Rotina'), ('closing', 'Fechamento')], max_length=20, verbose_name='momento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'template de checklist operacional',
                'verbose_name_plural': 'templates de checklists operacionais',
                'ordering': ['moment', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OperationTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição curta')),
                ('moment', models.CharField(choices=[('opening', 'Abertura'), ('routine', 'Rotina'), ('closing', 'Fechamento')], max_length=20, verbose_name='momento')),
                ('area', models.CharField(choices=[('cash', 'Caixa'), ('room', 'Salão'), ('production', 'Produção'), ('stock', 'Estoque'), ('cleaning', 'Limpeza'), ('management', 'Gestão')], max_length=20, verbose_name='área')),
                ('evidence_required', models.CharField(choices=[('none', 'Nenhuma'), ('text', 'Texto'), ('number', 'Número'), ('photo', 'Foto'), ('double_check', 'Dupla conferência')], default='none', max_length=20, verbose_name='evidência exigida')),
                ('expected_role', models.CharField(blank=True, max_length=80, verbose_name='responsável esperado')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('is_system', models.BooleanField(default=False, verbose_name='tarefa do sistema')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'template de tarefa operacional',
                'verbose_name_plural': 'templates de tarefas operacionais',
                'ordering': ['moment', 'sort_order', 'title'],
                'permissions': [('manage_operation_checklists', 'Pode configurar checklists operacionais'), ('perform_operation_task', 'Pode executar tarefas operacionais'), ('supervise_operation_task', 'Pode supervisionar tarefas operacionais'), ('view_operation_reports', 'Pode ver relatórios operacionais')],
            },
        ),
        migrations.CreateModel(
            name='OperationChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data operacional')),
                ('shift_ref', models.CharField(blank=True, default='', max_length=50, verbose_name='turno')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='open', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_checklists_completed', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_checklists_started', to=settings.AUTH_USER_MODEL, verbose_name='iniciado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='backstage.operationchecklisttemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'execução de checklist operacional',
                'verbose_name_plural': 'execuções de checklists operacionais',
                'ordering': ['-business_date', 'template__sort_order', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluída'), ('skipped', 'Ignorada'), ('blocked', 'Bloqueada')], default='pending', max_length=20, verbose_name='status')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('evidence_required', models.CharField(choices=[('none', 'Nenhuma'), ('text', 'Texto'), ('number', 'Número'), ('photo', 'Foto'), ('double_check', 'Dupla conferência')], default='none', max_length=20, verbose_name='evidência exigida')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executada em')),
                ('supervised_at', models.DateTimeField(blank=True, null=True, verbose_name='supervisionada em')),
                ('evidence_text', models.TextField(blank=True, verbose_name='evidência textual')),
                ('evidence_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='evidência numérica')),
                ('evidence_data', models.JSONField(blank=True, default=dict, verbose_name='evidência estruturada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('linked_domain', models.CharField(blank=True, max_length=80, verbose_name='domínio vinculado')),
                ('linked_ref', models.CharField(blank=True, max_length=120, verbose_name='ref vinculada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('checklist_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='backstage.operationchecklistrun', verbose_name='checklist')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_tasks_executed', to=settings.AUTH_USER_MODEL, verbose_name='executada por')),
                ('supervised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_tasks_supervised', to=settings.AUTH_USER_MODEL, verbose_name='supervisionada por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='backstage.operationtasktemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'execução de tarefa operacional',
                'verbose_name_plural': 'execuções de tarefas operacionais',
                'ordering': ['checklist_run', 'template__sort_order', 'template__title'],
            },
        ),
        migrations.CreateModel(
            name='OperationChecklistTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_required_override', models.BooleanField(blank=True, null=True, verbose_name='obrigatória neste checklist')),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='backstage.operationchecklisttemplate', verbose_name='checklist')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_links', to='backstage.operationtasktemplate', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'tarefa do template de checklist',
                'verbose_name_plural': 'tarefas do template de checklist',
                'ordering': ['sort_order', 'task_template__title'],
            },
        ),
        migrations.AddField(
            model_name='operationchecklisttemplate',
            name='tasks',
            field=models.ManyToManyField(related_name='checklist_templates', through='backstage.OperationChecklistTemplateTask', to='backstage.operationtasktemplate', verbose_name='tarefas'),
        ),
        migrations.AddConstraint(
            model_name='operationchecklistrun',
            constraint=models.UniqueConstraint(fields=('template', 'business_date', 'shift_ref'), name='backstage_operation_checklist_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationtaskrun',
            constraint=models.UniqueConstraint(fields=('checklist_run', 'template'), name='backstage_operation_task_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationchecklisttemplatetask',
            constraint=models.UniqueConstraint(fields=('checklist_template', 'task_template'), name='backstage_operation_template_task_unique'),
        ),
    ]
