# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def create_default_terminal(apps, schema_editor):
    POSTerminal = apps.get_model("backstage", "POSTerminal")
    CashShift = apps.get_model("backstage", "CashShift")
    channel_ref = getattr(settings, "SHOPMAN_POS_CHANNEL_REF", "pdv")
    terminal, _ = POSTerminal.objects.get_or_create(
        ref="pdv-main",
        defaults={
            "label": "PDV principal",
            "channel_ref": channel_ref,
            "is_active": True,
        },
    )
    CashShift.objects.filter(terminal__isnull=True).update(terminal=terminal)


def _append_note(notes: str, message: str) -> str:
    notes = (notes or "").strip()
    if not notes:
        return message
    return f"{notes}\n{message}"


def resolve_legacy_open_shift_conflicts(apps, schema_editor):
    POSTerminal = apps.get_model("backstage", "POSTerminal")
    CashShift = apps.get_model("backstage", "CashShift")
    now = timezone.now()

    duplicate_operator_rows = (
        CashShift.objects.filter(status="open")
        .values("operator_id")
        .annotate(open_count=Count("id"))
        .filter(open_count__gt=1)
    )
    for row in duplicate_operator_rows:
        shifts = list(
            CashShift.objects.filter(status="open", operator_id=row["operator_id"]).order_by("-opened_at", "-id")
        )
        for shift in shifts[1:]:
            shift.status = "void"
            shift.closed_at = shift.closed_at or now
            shift.notes = _append_note(
                shift.notes,
                "Voided by migration 0008 because this operator already had a newer open cash shift.",
            )
            shift.save(update_fields=["status", "closed_at", "notes"])

    duplicate_terminal_rows = (
        CashShift.objects.filter(status="open")
        .values("terminal_id")
        .annotate(open_count=Count("id"))
        .filter(open_count__gt=1)
    )
    for row in duplicate_terminal_rows:
        terminal = POSTerminal.objects.get(pk=row["terminal_id"])
        shifts = list(CashShift.objects.filter(status="open", terminal=terminal).order_by("-opened_at", "-id"))
        for shift in shifts[1:]:
            legacy_terminal, _ = POSTerminal.objects.get_or_create(
                ref=f"pdv-legacy-{shift.pk}",
                defaults={
                    "label": f"PDV legado {shift.pk}",
                    "channel_ref": terminal.channel_ref,
                    "location_ref": terminal.location_ref,
                    "is_active": terminal.is_active,
                    "metadata": {
                        "created_by_migration": "backstage.0008_cashshift_posterminal",
                        "split_from_terminal_ref": terminal.ref,
                    },
                },
            )
            metadata = dict(shift.metadata or {})
            migration_metadata = dict(metadata.get("migration_0008") or {})
            migration_metadata["split_from_terminal_ref"] = terminal.ref
            metadata["migration_0008"] = migration_metadata
            shift.terminal = legacy_terminal
            shift.metadata = metadata
            shift.notes = _append_note(
                shift.notes,
                f"Assigned to {legacy_terminal.ref} by migration 0008 to preserve concurrent open shifts.",
            )
            shift.save(update_fields=["terminal", "metadata", "notes"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0007_operationchecklisttemplate_operationtasktemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POSTerminal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.SlugField(max_length=80, unique=True, verbose_name="ref")),
                ("label", models.CharField(blank=True, default="", max_length=120, verbose_name="rotulo")),
                ("channel_ref", models.CharField(default="pdv", max_length=80, verbose_name="canal")),
                ("location_ref", models.CharField(blank=True, default="", max_length=120, verbose_name="local")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadados")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
            ],
            options={
                "verbose_name": "terminal POS",
                "verbose_name_plural": "terminais POS",
                "ordering": ["ref"],
            },
        ),
        migrations.RenameModel(
            old_name="CashRegisterSession",
            new_name="CashShift",
        ),
        migrations.RenameField(
            model_name="cashshift",
            old_name="closing_amount_q",
            new_name="blind_closing_amount_q",
        ),
        migrations.RenameField(
            model_name="cashmovement",
            old_name="session",
            new_name="shift",
        ),
        migrations.AddField(
            model_name="cashshift",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="terminal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_shifts",
                to="backstage.posterminal",
                verbose_name="Terminal",
            ),
        ),
        migrations.RunPython(create_default_terminal, noop_reverse),
        migrations.RunPython(resolve_legacy_open_shift_conflicts, noop_reverse),
        migrations.AlterField(
            model_name="cashshift",
            name="terminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_shifts",
                to="backstage.posterminal",
                verbose_name="Terminal",
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_shifts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operador",
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="blind_closing_amount_q",
            field=models.IntegerField(
                blank=True,
                help_text="Valor contado no fechamento cego em centavos.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="difference_q",
            field=models.IntegerField(
                blank=True,
                help_text="Diferenca: contado - esperado (positivo = sobra).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cashshift",
            name="status",
            field=models.CharField(
                choices=[("open", "Aberto"), ("closed", "Fechado"), ("void", "Cancelado")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cashmovement",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="backstage.cashshift",
                verbose_name="Turno",
            ),
        ),
        migrations.AlterModelOptions(
            name="cashshift",
            options={
                "ordering": ["-opened_at"],
                "permissions": [
                    ("operate_pos", "Pode operar o PDV (abrir/fechar caixa, sangria, balcão)"),
                    ("audit_cashshift", "Pode auditar turnos de caixa"),
                    ("adjust_cashshift", "Pode ajustar turnos de caixa"),
                ],
                "verbose_name": "Turno de Caixa",
                "verbose_name_plural": "Turnos de Caixa",
            },
        ),
        migrations.AlterModelOptions(
            name="dayclosing",
            options={
                "ordering": ["-date"],
                "permissions": [
                    ("perform_closing", "Pode executar fechamento do dia"),
                    ("view_production_reports", "Pode ver relatórios de produção"),
                    ("view_dayclosing_management", "Pode ver agregados gerenciais do fechamento"),
                ],
                "verbose_name": "fechamento do dia",
                "verbose_name_plural": "fechamentos do dia",
            },
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="open"),
                fields=("operator",),
                name="backstage_cashshift_open_operator_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="open"),
                fields=("terminal",),
                name="backstage_cashshift_open_terminal_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=models.Q(opening_amount_q__gte=0),
                name="backstage_cashshift_opening_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.CheckConstraint(
                condition=models.Q(blind_closing_amount_q__isnull=True)
                | models.Q(blind_closing_amount_q__gte=0),
                name="backstage_cashshift_blind_close_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(amount_q__gt=0),
                name="backstage_cashmovement_amount_positive",
            ),
        ),
    ]
