# Generated by Codex on 2026-05-16

from django.core.validators import RegexValidator
from django.db import migrations, models
from django.db.models import Q


def abandon_open_pos_tab_sessions(apps, schema_editor):
    Session = apps.get_model("orderman", "Session")
    Session.objects.filter(
        Q(handle_type="pos_tab") | Q(data__has_key="tab_code") | Q(data__has_key="tab_ref"),
        state="open",
    ).update(state="abandoned")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0008_cashshift_posterminal"),
        ("orderman", "0003_order_channel_external_ref_unique"),
    ]

    operations = [
        migrations.RunPython(abandon_open_pos_tab_sessions, noop_reverse),
        migrations.RenameField(
            model_name="postab",
            old_name="code",
            new_name="ref",
        ),
        migrations.AlterField(
            model_name="postab",
            name="ref",
            field=models.CharField(
                help_text="Referência curta da comanda. Números continuam normalizados com 8 dígitos; texto livre é aceito para identificação operacional.",
                max_length=64,
                unique=True,
                validators=[RegexValidator("^(?!\\s*$)[^/\\\\?#%\\r\\n\\t]{1,64}$", "Use até 64 caracteres, sem barras ou caracteres de URL.")],
                verbose_name="referência",
            ),
        ),
        migrations.AlterField(
            model_name="postab",
            name="label",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="rótulo"),
        ),
        migrations.AlterModelOptions(
            name="postab",
            options={"ordering": ["ref"], "verbose_name": "POS tab", "verbose_name_plural": "POS tabs"},
        ),
    ]
