# Generated by Django 5.2.11 on 2026-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0011_kdsticket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdsticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Operador deu baixa no card cancelado — sai do board.', null=True, verbose_name='ciente em'),
        ),
    ]
