# Generated by Django 6.0.5 on 2026-06-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0012_kdsticket_acknowledged_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayclosing',
            options={'ordering': ['-date'], 'permissions': [('perform_closing', 'Pode executar fechamento do dia'), ('view_production_reports', 'Pode ver relatórios de produção'), ('view_dayclosing_management', 'Pode ver agregados gerenciais do fechamento'), ('operate_production', 'Pode operar a produção (chão + planejamento) no app dedicado')], 'verbose_name': 'fechamento do dia', 'verbose_name_plural': 'fechamentos do dia'},
        ),
    ]
