# Generated by Django 6.0.5 on 2026-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_grant_operate_production'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='backstage_cashmovement_amount_positive',
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_q__gt', 0), models.Q(('movement_type', 'ajuste'), models.Q(('amount_q', 0), _negated=True)), _connector='OR'), name='backstage_cashmovement_amount_positive'),
        ),
    ]
