# Generated by Django 6.0.5 on 2026-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0015_remove_cashmovement_backstage_cashmovement_amount_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindPrepCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('recipe_ref', models.SlugField(max_length=100, verbose_name='preparo')),
                ('code', models.CharField(max_length=2, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'código de pesagem cega',
                'verbose_name_plural': 'códigos de pesagem cega',
                'constraints': [models.UniqueConstraint(fields=('date', 'recipe_ref'), name='blindprep_date_recipe_uq'), models.UniqueConstraint(fields=('date', 'code'), name='blindprep_date_code_uq')],
            },
        ),
    ]
