# Generated by Django 6.0.5 on 2026-07-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0016_blindprepcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashshift',
            options={'ordering': ['-opened_at'], 'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)'), ('audit_cashshift', 'Pode auditar turnos de caixa'), ('adjust_cashshift', 'Pode ajustar turnos de caixa'), ('manage_operators', 'Pode gerir operadores (resetar PIN, provisionar)')], 'verbose_name': 'Turno de Caixa', 'verbose_name_plural': 'Turnos de Caixa'},
        ),
    ]
