# Generated by Django 6.0.5 on 2026-07-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0020_alter_operatoralert_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'movimentação de caixa', 'verbose_name_plural': 'movimentações de caixa'},
        ),
        migrations.AlterModelOptions(
            name='cashshift',
            options={'ordering': ['-opened_at'], 'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)'), ('audit_cashshift', 'Pode auditar turnos de caixa'), ('adjust_cashshift', 'Pode ajustar turnos de caixa'), ('manage_operators', 'Pode gerir operadores (resetar PIN, provisionar)')], 'verbose_name': 'turno de caixa', 'verbose_name_plural': 'turnos de caixa'},
        ),
        migrations.AlterModelOptions(
            name='kdsinstance',
            options={'ordering': ['name'], 'verbose_name': 'estação KDS', 'verbose_name_plural': 'estações KDS'},
        ),
        migrations.AlterModelOptions(
            name='operationchecklisttemplate',
            options={'ordering': ['moment', 'sort_order', 'title'], 'verbose_name': 'modelo de checklist', 'verbose_name_plural': 'modelos de checklist'},
        ),
        migrations.AlterModelOptions(
            name='operationchecklisttemplatetask',
            options={'ordering': ['sort_order', 'task_template__title'], 'verbose_name': 'tarefa do modelo de checklist', 'verbose_name_plural': 'tarefas do modelo de checklist'},
        ),
        migrations.AlterModelOptions(
            name='operationtasktemplate',
            options={'ordering': ['moment', 'sort_order', 'title'], 'permissions': [('manage_operation_checklists', 'Pode configurar checklists operacionais'), ('perform_operation_task', 'Pode executar tarefas operacionais'), ('supervise_operation_task', 'Pode supervisionar tarefas operacionais'), ('view_operation_reports', 'Pode ver relatórios operacionais')], 'verbose_name': 'modelo de tarefa', 'verbose_name_plural': 'modelos de tarefa'},
        ),
        migrations.AlterModelOptions(
            name='postab',
            options={'ordering': ['ref'], 'verbose_name': 'comanda do PDV', 'verbose_name_plural': 'comandas do PDV'},
        ),
        migrations.AlterModelOptions(
            name='posterminal',
            options={'ordering': ['ref'], 'verbose_name': 'terminal do PDV', 'verbose_name_plural': 'terminais do PDV'},
        ),
    ]
