import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { formatCount } from '../app/utils/display'

const root = fileURLToPath(new URL('..', import.meta.url))
const surfaceRoots = ['app/pages', 'app/components']

function collectVueFiles (dir: string): string[] {
  const absolute = join(root, dir)
  const files: string[] = []
  for (const entry of readdirSync(absolute)) {
    const path = join(absolute, entry)
    const rel = relative(root, path)
    if (rel.startsWith('app/components/Ui')) continue
    if (statSync(path).isDirectory()) {
      files.push(...collectVueFiles(rel))
    } else if (path.endsWith('.vue')) {
      files.push(rel)
    }
  }
  return files
}

function read (path: string) {
  return readFileSync(join(root, path), 'utf8')
}

function templateOnly (source: string) {
  return source.match(/<template>([\s\S]*?)<\/template>/)?.[1] || ''
}

const surfaceVueFiles = surfaceRoots.flatMap(collectVueFiles)

describe('surface UX guardrails', () => {
  it('keeps native controls wrapped behind UI Thing components', () => {
    const offenders = surfaceVueFiles
      .filter(file => /<(button|input|select|textarea)\b/.test(read(file)))
      .map(file => relative(root, join(root, file)))

    expect(offenders).toEqual([])
  })

  it('does not expose architecture vocabulary or placeholder plurals in templates', () => {
    const forbidden = /\b(backend|projection|mutation|canonic|ChannelConfig|payload|idempotente|servidor)\b|item\(ns\)|pedido\(s\)|salvo\(s\)|Disponibilidade projetada|Total projetado|Busca, secoes/i
    const offenders = surfaceVueFiles
      .filter(file => forbidden.test(templateOnly(read(file))))
      .map(file => relative(root, join(root, file)))

    expect(offenders).toEqual([])
  })

  it('uses a single add-or-quantity action instead of zero-value steppers', () => {
    const addSurfaces = [
      'app/components/ProductTile.vue',
      'app/pages/product/[sku].vue'
    ]
    for (const file of addSurfaces) {
      expect(read(file)).toContain('<CartQuantityAction')
      expect(read(file)).not.toContain('<QuantityControl')
      expect(read(file)).not.toMatch(/lucide:(plus|minus)/)
    }

    expect(read('app/components/CartQuantityAction.vue')).toContain('<QuantityControl')
    expect(read('app/pages/cart.vue')).toContain('<QuantityControl')
  })

  it('does not revive stale projected quantities after cart removal', () => {
    const joined = surfaceVueFiles.map(read).join('\n')
    expect(joined).not.toMatch(/qtyForSku\([^)]*\)\s*\|\|\s*[^\n]*qty_in_cart/)
  })

  it('keeps storefront operational status sourced from shop_status', () => {
    const typeSource = read('app/types/shopman.ts')
    const omotenashiType = typeSource.match(/export interface OmotenashiProjection \{([\s\S]*?)\n\}/)?.[1] || ''

    expect(read('app/pages/index.vue')).not.toContain('home.omotenashi.is_open')
    expect(read('app/pages/index.vue')).toContain('home.value?.shop_status')
    expect(read('app/pages/index.vue')).toContain('contextualNotices')
    expect(read('app/pages/index.vue')).not.toContain("home.origin_channel === 'whatsapp'")
    expect(read('app/app.vue')).toContain('globalHomeNotice')
    expect(read('app/composables/useShopSession.ts')).toContain('homeNotices')
    expect(read('app/types/shopman.ts')).toContain('label: string')
    expect(read('app/types/shopman.ts')).toContain('export interface HomeNoticeProjection')
    expect(read('app/types/shopman.ts')).toContain('notices: HomeNoticeProjection[]')
    expect(read('app/pages/index.vue')).toContain("label: status?.label?.trim() || ''")
    expect(read('app/pages/index.vue')).not.toContain("label: isOpen ? 'Aberto agora' : 'Fechado agora'")
    expect(read('app/pages/index.vue')).not.toContain('v-if="operationalStatus.message"')
    expect(read('app/components/HomeHeroThing.vue')).not.toContain('omo.shop_hint')
    expect(omotenashiType).not.toMatch(/\b(is_open|opens_at|closes_at)\b/)
  })

  it('syncs backend projections with explicit watch sources instead of self-tracking effects', () => {
    const forbidden = /watchEffect\(\s*\(\)\s*=>[\s\S]{0,320}\b(setFromHome|setFromAuthSession|setFromServer)\(/
    const offenders = surfaceVueFiles
      .filter(file => forbidden.test(read(file)))
      .map(file => relative(root, join(root, file)))

    expect(offenders).toEqual([])
  })

  it('does not render a second command search field in the menu', () => {
    const menu = read('app/pages/menu.vue')

    expect(read('app/components/Ui/Listbox/Listbox.vue')).toContain('import { ListboxRoot, useForwardPropsEmits } from "reka-ui"')
    expect(read('app/components/Ui/Listbox/Item.vue')).toContain('import { ListboxItem, useForwardPropsEmits } from "reka-ui"')
    expect(read('app/components/Ui/Listbox/Filter.vue')).toContain('import { ListboxFilter, useForwardPropsEmits } from "reka-ui"')
    expect(menu).not.toContain('<UiCommandInput')
    expect(menu).not.toContain('<UiCommand')
    expect(menu).not.toContain('max-h-52')
    expect(menu).toContain('<UiInputGroup')
    expect(menu).toContain('placeholder="Buscar no cardápio"')
    expect(menu).toContain('class="sr-only" aria-live="polite"')
    expect(menu).toContain('searchPanelOpen')
    expect(menu).toContain('openSearchPanel')
    expect(menu).toContain('closeSearchPanel')
    expect(menu).toContain('sectionOptions')
    expect(menu).toContain('filteredCount')
    expect(menu).toContain('uniqueItems')
    expect(menu).toContain('uniqueItemsBySku')
    expect(menu).toContain('sectionsBySku')
    expect(menu).toContain('searchOrFilterMode')
    expect(menu).toContain('searchPanelView')
    expect(menu).toContain('sectionBySku')
    expect(menu).toContain("from '~/presentation/menu'")
    expect(menu).toContain('filteredSections')
    expect(menu).not.toContain('function collectionSearchScore')
    expect(menu).not.toContain('function productSearchScore')
    expect(menu).not.toContain('function matchesProductAcrossCatalog')
    const menuPresentation = read('app/presentation/menu.ts')
    expect(menuPresentation).toContain('export function collectionSearchScore')
    expect(menuPresentation).toContain('export function productSearchScore')
    expect(menuPresentation).toContain('export function keywordSearchOptions')
    expect(menuPresentation).toContain('export function tileBadge')
    expect(menu).toContain('data-menu-filterbar')
    expect(menu).toContain('<main class="min-w-0">')
    expect(menu).toContain('<h1 class="sr-only">Cardápio</h1>')
    expect(menu.indexOf('<UiBreadcrumbs')).toBeGreaterThan(menu.indexOf('<div class="shop-section">'))
    expect(menu).toContain('border-y bg-background shadow-sm')
    expect(menu).not.toContain('bg-background/92')
    expect(menu).not.toContain('backdrop-blur supports-[backdrop-filter]:bg-background/78')
    expect(menu).not.toContain('[margin-left:calc(50%_-_50vw)]')
    expect(menu).not.toContain('<h1 class="text-2xl')
    expect(menu).toContain('data-menu-pillrail')
    expect(menu).toContain('data-menu-pill-ref')
    expect(menu).toContain('data-menu-pillrail-tail')
    expect(menu).toContain('pillRailTailWidth')
    expect(menu).toContain('nearDocumentEnd')
    expect(menu).toContain('@update:model-value="selectSection"')
    // Painel leve: chips filtram ao vivo, produtos navegam. Sem listbox,
    // sem funil por linha, sem "Aplicar" em dois passos.
    expect(menu).toContain('data-menu-search-panel')
    expect(menu).toContain('data-menu-filter-chips')
    expect(menu).toContain('data-menu-product-results')
    expect(menu).not.toContain('<UiListbox')
    expect(menu).not.toContain('Aplicar filtro')
    expect(menu).toContain('toggleMenuFilter')
    expect(menu).toContain(':aria-pressed="isFilterApplied(chip.key)"')
    expect(menu).toContain('hasAppliedFilters')
    expect(menu).toContain('FILTERED_SECTION_VALUE')
    expect(menu).toContain('data-menu-clear-filter-pill')
    expect(menuPresentation).toContain('export function itemMatchesAnyFilter')
    expect(menuPresentation).toContain("kind: 'collection'")
    expect(menuPresentation).toContain("kind: 'product'")
    expect(menuPresentation).toContain("kind: 'keyword'")
    expect(menu).toContain('lucide:funnel')
    expect(menu).toContain('<span v-if="searchOrFilterMode"')
    expect(menu).not.toContain('<UiItemGroup')
    expect(menu).not.toContain('hasAppliedProductFilter')
    expect(menu).not.toContain('sectionBySku.get(item.sku)?.label')
    expect(menu).not.toMatch(/return allItems\.value\s+\.filter\(item => matches\(item/)
    expect(menu).not.toContain('const count = allItems.value.filter')
    expect(menu).toContain('scrollToSection')
    expect(menu).toContain('syncActiveSectionFromScroll')
    expect(menu).toContain('data-menu-section-ref')
    expect(menu).toContain('if (searchPanelOpen.value) closeSearchPanel()')
    expect(menu).not.toContain('sections.value.filter(section => section.ref === activeSection.value)')
  })

  it('renders the menu product grid once instead of duplicating it in hidden tab panels', () => {
    const menu = read('app/pages/menu.vue')

    expect(menu).not.toMatch(/<UiTabsContent[\s\S]*?v-for=/)
    expect((menu.match(/<ProductListItem/g) || [])).toHaveLength(1)
    expect(menu).not.toContain('<ProductTile')
  })

  it('uses canonical Card defaults intentionally for product media cards', () => {
    const productTile = read('app/components/ProductTile.vue')
    const home = read('app/pages/index.vue')

    expect(read('app/components/Ui/Card/Card.vue')).toContain('base: "bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm"')
    expect(read('app/components/Ui/AspectRatio.vue')).toContain('data-slot="aspect-ratio"')
    expect(read('app/components/Ui/AspectRatio.vue')).toContain('import { AspectRatio } from "reka-ui"')
    expect(productTile).toContain('<UiCard class="gap-0 overflow-hidden py-0" data-product-tile>')
    expect(productTile).toContain('<UiAspectRatio :ratio="4 / 3" class="overflow-hidden bg-muted">')
    expect(productTile).toContain('class="size-full object-cover"')
    expect(productTile).toContain(':to="productRoute(item.sku)"')
    expect(productTile).toContain(':aria-label="`Ver detalhes de ${item.name}`"')
    expect(productTile).toContain("import { tileBadge } from '~/presentation/menu'")
    expect(productTile).toContain('v-if="badge"')
    expect(productTile).not.toContain('<UiPopover')
    expect(productTile).not.toContain('availabilityVariant')
    expect(productTile).not.toContain('item.allergens.length || item.available_qty')
    expect(productTile).not.toContain('Alérgenos:')
    expect(productTile).not.toContain('<UiHoverCard')
    expect(productTile).not.toContain('Detalhes</UiButton>')
    expect(productTile).not.toContain('defineEmits')
    expect(productTile).not.toContain('lucide:info')
    expect(read('app/pages/menu.vue')).not.toContain('@select="openProduct"')
    expect(read('app/pages/menu.vue')).not.toContain('ProductDetailSheet')
    expect(read('app/pages/menu.vue')).not.toContain('detailOpen')
    expect(read('app/pages/menu.vue')).not.toContain('openProduct')
    expect(read('app/types/shopman.ts')).toContain('unit_weight_label: string | null')
    expect(read('app/utils/display.ts')).toContain('compactUnitWeightLabel')
    expect(productTile).toContain('compactUnitWeightLabel(item.unit_weight_label)')
    expect(productTile).toContain('class="flex flex-wrap items-end justify-between gap-x-3 gap-y-2"')
    expect(productTile).toContain('<div class="ml-auto shrink-0">')
    expect(productTile).not.toContain('<UiCardFooter class="mt-auto flex items-center justify-end gap-2')
    expect(read('app/pages/product/[sku].vue')).toContain('{{ product.unit_weight_label }}')
    expect(read('app/pages/product/[sku].vue')).toContain('compactUnitWeightLabel(product.unit_weight_label)')
    expect(home).toContain('<ProductTile v-for="item in featuredPreview"')
    expect(home).not.toContain('<UiCard v-for="item in featured')
    expect(home).not.toContain('<CartQuantityAction')
  })

  it('renders the home hero as a canonical carousel without a tabbed landing panel', () => {
    const hero = read('app/components/HomeHeroThing.vue')
    const home = read('app/pages/index.vue')

    expect(hero).not.toContain('<UiTabs')
    expect(hero).not.toContain('<UiTabsTrigger')
    expect(hero).not.toContain('<UiTabsContent')
    expect(hero).toContain('interface HeroSlide')
    expect(hero).toContain('const slides = computed<HeroSlide[]>')
    expect(hero).toContain("ref: 'birthday'")
    expect(hero).toContain("ref: 'order'")
    expect(hero).toContain("ref: 'reorder'")
    expect(hero).toContain("ref: 'handmade'")
    expect(hero).toMatch(/ref: 'greeting',\n\s+titleLines: \[greetingTitle\],\n\s+imageUrl/)
    expect(hero).toMatch(/ref: 'greeting-return',\n\s+titleLines: \[greetingTitle\],\n\s+imageUrl/)
    expect(hero).toContain('copy.reorder_title_prefix')
    expect(hero).toContain('copy.handmade_title_prefix')
    expect(hero).toContain('data-home-hero-carousel')
    expect(hero).toContain('aria-roledescription="carousel"')
    expect(hero).toContain('min-h-[calc(100svh-4rem)]')
    expect(hero).toContain('-mx-4 overflow-hidden rounded-none')
    expect(hero).toContain('items-center justify-center')
    expect(hero).toContain('text-center text-white')
    expect(hero).toContain('activateNextSlide')
    expect(hero).toContain('UiButton')
    expect(home).toContain('<main class="bg-muted">')
    expect(home).toContain('<section class="bg-muted pb-6 pt-0 sm:py-8 lg:py-10">')
    expect(home).toContain(':reorder-action="reorderAction"')
    expect(home).toContain('@reorder="handleReorder"')
    expect(home).toContain('sectionsCopy.availability_heading.title')
    expect(home).toContain('sectionsCopy.how_it_works_heading.title')
    expect(home).toContain('sectionsCopy.whatsapp_cta.title')
    expect(home).toContain('class="shop-section border-y bg-background pt-10 md:pt-12"')
    expect(home).toContain('class="shop-section bg-muted"')
    expect(home).toContain('class="border-y bg-background py-0 sm:py-8 lg:py-10"')
    expect(home).toContain('class="relative -mx-4 overflow-hidden rounded-none bg-foreground text-background sm:mx-0 sm:rounded-lg"')
    expect(home).not.toContain('v-if="operationalStatus.message"')
    expect(home).toContain('data-home-reorder-card')
    expect(home).toContain('const quickReorderImageItem = computed')
    expect(home).toContain('<UiCard v-if="reorderAction || quickReorderItems.length" class="gap-0 overflow-hidden py-0" data-home-reorder-card>')
    expect(home).toContain('<div class="grid grid-cols-1 md:grid-cols-2">')
    expect(home).toContain('<UiAspectRatio :ratio="16 / 9" class="overflow-hidden bg-muted md:h-full">')
    expect(home).not.toContain('class="mx-auto max-w-3xl"')
    expect(home).not.toContain('filled')
    expect(home).not.toContain('Voltar ao que funcionou')
  })

  it('keeps checkout authentication driven by the projection contract', () => {
    const checkout = read('app/pages/checkout.vue')
    const checkoutFlow = read('app/utils/checkoutFlow.ts')
    const types = read('app/types/shopman.ts')

    expect(checkout).toContain('buildCheckoutPayload')
    expect(checkout).toContain("from '~/utils/checkoutFlow'")
    expect(checkout).toContain('checkout.value.requires_authentication')
    expect(checkout).toContain('checkout.value?.auth_action')
    expect(checkout).toContain('navigateTo(authRoute.value)')
    expect(checkoutFlow).toContain("export type CheckoutStep = 'fulfillment' | 'address' | 'when' | 'payment'")
    expect(checkoutFlow).toContain('export function checkoutSteps')
    expect(checkoutFlow).toContain('export function checkoutStepState')
    expect(checkoutFlow).toContain('export function checkoutStepHeaderSummary')
    expect(checkoutFlow).toContain('export function reconciledPickupSlotRef')
    expect(checkout).toContain('validateContact')
    expect(checkout).toContain('contactEditing')
    expect(checkout).toContain('phoneDisplay')
    expect(checkout).toContain('data-checkout-contact-card')
    expect(checkout).not.toContain('id="checkout-phone"')
    expect(checkout).not.toContain('continueFromIdentity')
    expect(checkout).toContain('continueFromFulfillment')
    expect(checkout).toContain('continueFromAddress')
    expect(checkout).toContain('continueFromWhen')
    expect(checkout).toContain('continueFromPayment')
    expect(checkout).toContain('fieldErrors.delivery_date')
    expect(checkout).toContain('state.delivery_date = localDateValue(today)')
    expect(checkout).not.toContain("type Step = 'identity'")
    expect(checkout).toContain('data-checkout-progress-stack')
    expect(checkout).toContain('data-checkout-step="fulfillment"')
    expect(checkout).toContain('data-checkout-step="address"')
    expect(checkout).toContain('data-checkout-step="when"')
    expect(checkout).toContain('data-checkout-step="payment"')
    expect(checkout).not.toContain('<UiTabsContent value="review">')
    expect(checkout).not.toContain('<UiTabs')
    expect(checkout).not.toContain('<UiStepper')
    expect(checkout).not.toContain('<UiAlertDialog')
    expect(checkout).toContain('confirmOpen')
    expect(checkout).toContain('openConfirmSheet')
    expect(checkout).toContain('<UiSheet v-model:open="confirmOpen">')
    expect(checkout).toContain('side="bottom"')
    expect(checkout).toContain('variant="floating"')
    expect(checkout).toContain('<CheckoutProgressSection')
    expect(checkout).toContain('stepState')
    expect(read('app/components/CheckoutProgressSection.vue')).toContain(':data-checkout-section-state="state"')
    expect(checkout).toContain('<UiRadioGroup v-model="state.fulfillment_type" class="grid gap-2 sm:grid-cols-2">')
    expect(checkout).toContain('<UiRadioGroup v-model="state.payment_method" class="grid gap-2 sm:grid-cols-2">')
    expect(checkout).toContain('<UiFieldLabel v-if="availableFulfillment.includes(\'pickup\')" for="checkout-fulfillment-pickup">')
    expect(checkout).toContain('<UiFieldLabel v-for="method in paymentMethods"')
    expect(checkout).toContain('<UiField orientation="horizontal">')
    expect(checkout).toContain('<UiFieldContent>')
    expect(checkout).toContain('paymentIcon(method.ref)')
    expect(checkout).toContain('{{ method.label }}')
    expect(checkout).not.toContain('class="flex gap-3 rounded-lg border p-4"')
    expect(checkout).not.toContain('<label v-for="method in paymentMethods"')
    expect(checkout).toContain('Confirmar pedido')
    expect(checkout).toContain('confirmItemSummary')
    expect(checkout).toContain('paymentMethodLabel')
    expect(checkout).toContain('fulfillmentSummary')
    expect(checkout).toContain('data-checkout-live-summary')
    expect(checkout).toContain('<CartSummaryBreakdown v-if="cart" :cart="cart" compact />')
    expect(checkout).not.toContain('sticky bottom-20')
    expect(checkout).toContain('Total do pedido')
    expect(checkout).toContain('checkoutActionLabel')
    expect(checkout).toContain('Revisar pedido')
    expect(checkout).not.toContain('Enviar pedido')
    expect(checkout).not.toContain('Compra sem senha')
    expect(types).toContain('requires_authentication: boolean')
    expect(types).toContain('auth_action: Action | null')
  })

  it('keeps checkout entry points visible before authentication', () => {
    const app = read('app/app.vue')
    const bottomNav = read('app/components/AppBottomNav.vue')
    const header = read('app/components/ShopHeader.vue')
    const cartState = read('app/composables/useCartState.ts')
    const cartPage = read('app/pages/cart.vue')
    const home = read('app/pages/index.vue')
    const types = read('app/types/shopman.ts')
    const reorder = read('app/composables/useReorder.ts')

    expect(types).toContain('actions: Action[]')
    expect(app).not.toContain('<CartDrawer')
    expect(cartState).not.toContain('drawerOpen')
    expect(cartState).toContain("await navigateTo('/cart')")
    expect(reorder).not.toContain('drawerOpen')
    expect(reorder).toContain("await navigateTo('/cart')")
    expect(bottomNav).not.toContain("label: 'Finalizar'")
    expect(bottomNav).not.toContain("to: '/checkout'")
    expect(bottomNav).toContain("to: '/cart'")
    expect(bottomNav).not.toContain('drawerOpen')
    expect(bottomNav).toContain('cartPulse')
    expect(bottomNav).toContain('scale-125 ring-2 ring-primary/25')
    expect(header).not.toContain("label: 'Finalizar'")
    expect(header).not.toContain("to: '/checkout'")
    expect(header).toContain('to="/cart"')
    expect(header).toContain('aria-label="Ver carrinho"')
    expect(header).toContain('cartPulse')
    expect(header).toContain('class="hidden md:inline-flex"')
    expect(header).toContain('<header class="sticky top-0 z-40 border-b bg-background">')
    expect(header).toContain('<Icon name="lucide:store" class="size-5" />')
    // Mobile: a bottom-nav é a navegação primária; o header não duplica menu.
    expect(header).not.toContain('mobileMenuOpen')
    expect(header).not.toContain('UiSheet')
    expect(header).not.toContain('icon="lucide:menu"')
    expect(bottomNav).toContain("to: '/menu'")
    expect(bottomNav).toContain("to: '/account'")
    expect(header).not.toContain('shopping-basket')
    expect(header).not.toContain('bg-primary text-primary-foreground')
    expect(header).not.toContain('session.shop.value?.tagline')
    expect(header).not.toContain('Compra rápida e acompanhada')
    expect(home).not.toContain('fixed bottom-20 right-4')
    expect(home).not.toContain('@click="drawerOpen = true"')
    expect(cartPage).toContain("action.ref === 'checkout'")
    expect(cartPage).toContain("checkoutAction?.label || 'Finalizar pedido'")
    expect(cartPage).toContain('<CartSummaryBreakdown :cart="cart" />')
    expect(cartPage).toContain('sticky bottom-20')
    expect(cartPage).toContain('cartIssue')
    expect(cartPage).toContain('rateLimitRecovery')
    expect(cartPage).toContain('acceptAvailableQty')
    expect(cartPage).toContain('retryLastMutation')
    expect(cartPage).not.toContain(':disabled="cart.is_empty || cart.has_unavailable_items"')
  })

  it('keeps mobile product add controls explicit before switching to quantity editing', () => {
    const action = read('app/components/CartQuantityAction.vue')
    const quantity = read('app/components/QuantityControl.vue')
    const productRoute = read('app/pages/product/[sku].vue')
    const cartState = read('app/composables/useCartState.ts')
    const smoke = read('scripts/ux-smoke.mjs')

    expect(action).toContain('addTargetQty')
    expect(action).toContain("tone?: 'default' | 'inverted'")
    expect(action).toContain("const nextQty = props.addTargetQty ?? 1")
    expect(action).toContain("tone === 'inverted' ? 'secondary' : 'default'")
    // Pílula opaca (padrão iFood): nunca campo de form transparente sobre foto/CTA.
    expect(quantity).toContain('rounded-full border bg-background text-foreground shadow-sm')
    expect(quantity).not.toContain('<UiNumberField')
    expect(productRoute).toContain('const mobileCtaTouched = ref(false)')
    expect(productRoute).toContain('const mobileCtaQty = computed(() => mobileCtaTouched.value ? currentQty.value : 0)')
    expect(productRoute).toContain('class="sticky bottom-20 z-30 mt-5 rounded-lg border border-foreground bg-foreground p-3 text-background shadow-lg md:hidden"')
    expect(productRoute).toContain(':qty="mobileCtaQty"')
    expect(productRoute).toContain(':add-target-qty="mobileCtaAddTarget"')
    expect(productRoute).toContain('tone="inverted"')
    expect(productRoute).toContain('@changed="mobileCtaTouched = true"')
    expect(cartState).not.toContain('drawerOpen')
    expect(smoke).toContain('cart page entry point should remain visible after add')
  })

  it('renders a projection-driven web footer in the shell', () => {
    const app = read('app/app.vue')
    const footer = read('app/components/ShopFooter.vue')
    const session = read('app/composables/useShopSession.ts')

    expect(app).toContain('<ShopFooter')
    expect(app).toContain('id="main-content"')
    expect(app).toContain('Pular para o conteúdo')
    expect(app).toContain('shopStatusMessage')
    expect(footer).toContain('session.shop.value')
    expect(footer).toContain('session.openingHours.value')
    expect(footer).not.toContain('openingHours.slice')
    expect(footer).toContain('<footer class="border-t bg-background">')
    expect(footer).not.toContain('bg-muted/40')
    expect(footer).toContain('Falar no WhatsApp')
    expect(session).toContain('openingHours')
  })

  it('keeps login copy and recovery actions projection-driven', () => {
    const login = read('app/pages/login.vue')
    const authPhone = read('app/utils/authPhone.ts')

    expect(login).toContain("apiPath('/api/v1/storefront/home/')")
    expect(login).toContain('home.auth_copy')
    expect(login).toContain('home.public_config.whatsapp_url')
    expect(login).toContain('const isCheckoutReturn')
    expect(login).toContain('const stepTitle')
    expect(login).toContain('const stepDescription')
    expect(login).toContain('<UiInputGroup>')
    expect(login).toContain('<UiInputGroupAddon align="inline-start">')
    expect(login).toContain('<UiInputGroupInput')
    expect(login).toContain('name="phone"')
    expect(login).toContain('phoneRegion')
    expect(login).toContain('togglePhoneRegion')
    expect(login).toContain('authPhonePayload')
    expect(authPhone).toContain('phone_region')
    expect(authPhone).toContain('phone_normalized')
    expect(authPhone).toContain('target')
    expect(login).toContain("requestCode('whatsapp', $event)")
    expect(login).toContain("requestCode('sms', $event)")
    expect(login).toContain('class="w-full justify-center"')
    expect(login).toContain('<UiItem v-if="supportUrl" variant="outline">')
    expect(login).toContain('<UiFieldLabel for="trusted-device" class="w-full">')
    expect(login).not.toContain('<UiButtonGroup')
    expect(login).not.toContain('max-w-xl')
    expect(login).not.toContain('class="rounded-md border p-3"')
    expect(login).toContain('response.dev_console_hint')
    expect(login).toContain('response.debug_otp_code')
    expect(login).toContain('data-testid="debug-otp-alert"')
    expect(login).toContain('debugOtpCode = ref')
    expect(login).toContain('Código no terminal local')
    expect(login).toContain('as="h1"')
  })

  it('uses scaffolded UI Thing components for OTP, empty states and structured fields', () => {
    const login = read('app/pages/login.vue')
    const menu = read('app/pages/menu.vue')
    const productRoute = read('app/pages/product/[sku].vue')
    const upsellRail = read('app/components/CartUpsellRail.vue')
    const cartPage = read('app/pages/cart.vue')

    expect(read('app/components/Ui/PinInput/PinInput.vue')).toContain('PinInputRoot')
    expect(read('app/components/Ui/Field/Field.vue')).toContain('data-slot="field"')
    expect(read('app/components/Ui/Empty/Empty.vue')).toContain('data-slot="empty"')
    expect(read('app/components/Ui/DescriptionList/DescriptionList.vue')).toContain('data-slot="description-list"')
    expect(read('app/components/Ui/ScrollArea/ScrollArea.vue')).toContain('ScrollAreaRoot')
    expect(read('app/components/Ui/InputGroup/InputGroup.vue')).toContain('data-slot="input-group"')

    expect(login).toContain('<UiPinInput')
    expect(login).toContain('<UiField')
    expect(login).toContain('<UiInputGroup')
    expect(login).not.toContain('id="login-code" v-model="code"')
    expect(cartPage).toContain('<UiEmpty')
    expect(menu).toContain('<UiEmpty')
    expect(productRoute).toContain('<UiDescriptionList')
    expect(productRoute).toContain('<UiCard class="pb-0">')
    expect(productRoute).toContain('<UiCardContent class="space-y-5">')
    expect(productRoute).toContain('<UiAccordion type="multiple" class="w-full border-t">')
    expect(productRoute).not.toContain('<UiAccordion type="multiple" class="mt-2 border-t">')
    expect(productRoute).not.toContain('<UiAccordion type="multiple" class="rounded-lg border bg-card">')
    expect(upsellRail).toContain('<UiItem variant="outline" size="sm" class="w-44 items-stretch gap-3 bg-card p-3">')
    expect(upsellRail).toContain('<UiItemHeader>')
    expect(upsellRail).toContain('function productRoute (sku: string)')
    expect(upsellRail).toContain(':to="productRoute(upsell.sku)"')
    expect(upsellRail).toContain('class="block w-full rounded-md"')
    expect(upsellRail).toContain(':aria-label="`Ver detalhes de ${upsell.name}`"')
    expect(upsellRail).toContain('<UiItemMedia v-if="upsell.image_url" variant="image"')
    expect(upsellRail).toContain('aspect-[4/3]')
    expect(upsellRail).toContain('<UiItemFooter class="w-full">')
    expect(upsellRail).toContain('<div class="w-full [&>button]:w-full">')
    expect(upsellRail).toContain('<CartQuantityAction')
  })

  it('keeps cart lines editable with explicit remove instead of hidden decrement removal', () => {
    const cartPage = read('app/pages/cart.vue')
    const quantity = read('app/components/QuantityControl.vue')

    expect(quantity).toContain('minQty')
    expect(cartPage).toContain(':min-qty="1"')
    expect(cartPage).toContain('removeLine(line)')
    expect(cartPage).toContain('data-cart-items-card')
    expect(cartPage).toContain('data-cart-line-item')
    expect(cartPage).toContain('grid grid-cols-[5rem_minmax(0,1fr)] items-stretch gap-3 rounded-none border-0 border-b bg-card p-3 last:border-b-0 sm:grid-cols-[6rem_minmax(0,1fr)] sm:gap-4 sm:p-4')
    expect(cartPage).toContain('<UiItemMedia v-if="line.image_url" variant="image"')
    expect(cartPage).toContain('<UiItemContent class="min-w-0 self-stretch">')
    expect(cartPage).toContain('icon="lucide:trash-2"')
    expect(cartPage).toContain(':aria-label="`Remover ${line.name}`"')
    expect(cartPage).toContain('<div class="mt-auto flex flex-wrap items-center justify-between gap-3 pt-3">')
    expect(cartPage).toContain('{{ line.qty }} × {{ line.price_display }} cada')
    expect(cartPage).toContain('{{ line.total_display }}')
    expect(cartPage).toContain('<CartUpsellRail v-if="cart.upsell"')
  })

  it('shows coupon savings as signed discounts without losing the original subtotal', () => {
    const summary = read('app/components/CartSummaryBreakdown.vue')
    const cartPage = read('app/pages/cart.vue')

    expect(summary).toContain("import type { CartProjection } from '~/types/shopman'")
    expect(summary).toContain('cart.has_discount')
    expect(summary).toContain('cart.original_subtotal_display')
    expect(summary).toContain('line-through')
    expect(summary).toContain('discountDisplay(discount.amount_display)')
    expect(summary).toContain("return value.startsWith('-') ? value : `- ${value}`")
    expect(cartPage).not.toContain('{{ cart.subtotal_display }}</span>')
    expect(cartPage).toContain('<UiCardTitle>Cupom</UiCardTitle>')
    expect(cartPage).toContain('<UiItem v-if="cart.coupon_code" variant="outline" size="sm" class="bg-card">')
    expect(cartPage).toContain('<Icon name="lucide:ticket-percent" />')
  })

  it('uses Field for account preference switches and Item for trusted devices', () => {
    const account = read('app/pages/account.vue')

    expect(account).toContain('const accountTabsRootClass =')
    expect(account).toContain("const accountTabsRootClass = 'gap-0'")
    expect(account).toContain('const accountTabsPanelClass =')
    expect(account).toContain("const accountTabsPanelClass = 'gap-0 overflow-hidden py-0'")
    expect(account).toContain("apiPath('/api/v1/account/devices/')")
    expect(account).toContain("apiPath('/api/v1/account/profile/')")
    expect(account).toContain("apiPath('/api/v1/account/export/')")
    expect(account).toContain("apiPath('/api/v1/account/delete/')")
    expect(account).toContain('const accountTabsHeaderClass =')
    expect(account).toContain("const accountTabsHeaderClass = 'after:bg-border relative gap-0 bg-card px-4 py-1.5 sm:px-6 after:absolute after:inset-x-0 after:bottom-0 after:h-px'")
    expect(account).toContain('const accountTabsListClass =')
    expect(account).toContain('h-auto w-full justify-start gap-1.5 overflow-x-auto rounded-none bg-transparent p-0')
    expect(account).toContain('const accountTabsTriggerClass =')
    expect(account).toContain('min-w-max rounded-md px-3 py-1.5 data-[state=active]:bg-muted')
    expect(account).toContain('const accountTabsContentClass =')
    expect(account).toContain("const accountTabsContentClass = 'm-0'")
    expect(account).toContain('<UiTabs v-else v-model="activeTab" :class="accountTabsRootClass">')
    expect(account).toContain('<UiCardHeader :class="accountTabsHeaderClass">')
    expect(account).toContain('<UiTabsList :class="accountTabsListClass">')
    expect(account).toContain('<UiTabsTrigger value="profile" :class="accountTabsTriggerClass">Perfil</UiTabsTrigger>')
    expect(account).toContain('<UiTabsTrigger value="devices" :class="accountTabsTriggerClass">Aparelhos</UiTabsTrigger>')
    expect(account).toContain('<UiCard :class="accountTabsPanelClass">')
    expect(account).toContain('<UiCardContent class="px-4 py-4 sm:px-6">')
    expect(account).toContain('<UiTabsContent value="overview" :class="accountTabsContentClass">')
    expect(account).toContain('<UiTabsContent value="profile" :class="accountTabsContentClass">')
    expect(account).toContain('saveProfile')
    expect(account).toContain('exportData')
    expect(account).toContain('deleteAccountAcknowledged')
    expect(account).toContain('deleteAccount')
    expect(account).toContain('Salvar perfil')
    expect(account).toContain('Exportar meus dados')
    expect(account).toContain('Excluir minha conta')
    expect(account).toContain('<UiFieldSet class="rounded-lg border bg-background p-4">')
    expect(account).toContain('<UiFieldLegend>Preferências alimentares</UiFieldLegend>')
    expect(account).toContain('<UiFieldLabel')
    expect(account).toContain('orientation="horizontal"')
    expect(account).toContain('<UiSwitch')
    expect(account).toContain('v-for="pref in summary?.food_preferences || []"')
    expect(account).toContain('v-for="pref in summary?.notification_preferences || []"')
    expect(account).toContain('<UiItemGroup v-else class="gap-3">')
    expect(account).toContain('<UiItem v-for="device in accountDevices" :key="device.id" variant="outline" class="bg-background">')
    expect(account).toContain('<UiItemMedia variant="icon"')
    expect(account).toContain('askRevokeDevice(device)')
    expect(account).toContain('confirmRevokeDevice')
    expect(account).not.toContain('<UiTabsList :pill="false" :class="accountTabsListClass">')
    expect(account).not.toContain('rounded-b-none border-x border-t')
    expect(account).not.toContain('<label v-for="pref')
    expect(account).not.toContain('<UiFieldLabel\n                    v-for="pref')
    expect(account).not.toContain('class="flex items-center justify-between rounded-lg border p-3"')
  })

  it('lets authenticated customers add and edit addresses with UI Thing form controls', () => {
    const account = read('app/pages/account.vue')

    expect(account).toContain("apiPath('/api/v1/account/addresses/')")
    expect(account).toContain('refresh: refreshAddresses')
    expect(account).toContain('openCreateAddress')
    expect(account).toContain('openEditAddress(address)')
    expect(account).toContain('saveAddress')
    expect(account).toContain('addressPayload')
    expect(account).toContain('setDefaultAddress(address)')
    expect(account).toContain('askDeleteAddress(address)')
    expect(account).toContain('deleteAddress')
    expect(account).toContain("method: 'POST'")
    expect(account).toContain("method: 'PATCH'")
    expect(account).toContain("method: 'DELETE'")
    expect(account).toContain('<UiSheet v-model:open="addressSheetOpen">')
    expect(account).toContain('<UiAlertDialog v-model:open="addressDeleteOpen">')
    expect(account).toContain('<UiSelect v-model="addressForm.label">')
    expect(account).toContain('<UiTextarea')
    expect(account).toContain('<UiSwitch id="account-address-default"')
    expect(account).toContain('Adicionar endereço')
    expect(account).toContain('Editar endereço')
    expect(account).not.toMatch(/<(button|input|select|textarea)\b/)
  })

  it('keeps badges discreet and reserves success tone for explicit alerts', () => {
    const offenders = surfaceVueFiles
      .filter(file => /<UiBadge[^>]*variant="success"/.test(read(file)))
      .map(file => relative(root, join(root, file)))

    expect(offenders).toEqual([])
    expect(read('app/utils/display.ts')).toContain("availability === 'available') return 'secondary'")
    expect(read('app/utils/display.ts')).not.toContain("availability === 'available') return 'success'")
  })

  it('keeps destructive promise alerts readable instead of full red banners', () => {
    const tracking = read('app/pages/tracking/[ref].vue')
    const payment = read('app/pages/pedido/[ref]/pagamento.vue')
    const css = read('app/assets/css/tailwind.css')

    expect(css).toContain('--destructive-foreground: oklch(0.985 0 0)')
    expect(tracking).toContain('variant="default"')
    expect(tracking).toContain(':class="statusPanelClass"')
    expect(tracking).toContain('border-l-4 border-border border-l-destructive bg-card text-foreground shadow-sm')
    expect(tracking).toContain(':icon-class="statusPanelIconClass"')
    expect(tracking).toContain('lucide:triangle-alert')
    expect(payment).toContain(':filled="payment.promise.tone !== \'danger\'"')
    expect(payment).toContain('lucide:triangle-alert')
  })

  it('does not submit projected sensitive actions without idempotency when declared', () => {
    const tracking = read('app/pages/tracking/[ref].vue')
    const payment = read('app/pages/pedido/[ref]/pagamento.vue')

    for (const source of [tracking, payment]) {
      expect(source).toContain("action.idempotency === 'required' || action.idempotency === 'recommended'")
      expect(source).toContain("headers['x-idempotency-key'] = newRemoteMutationKey(action.ref)")
    }
  })

  it('keeps tracking recovery actionable and avoids repeated promise copy', () => {
    const tracking = read('app/pages/tracking/[ref].vue')

    expect(tracking).toContain('const { performAction: performReorderAction, conflict, pending: reorderPending } = useReorder()')
    expect(tracking).toContain('const reorderAction = computed')
    expect(tracking).toContain('const statusPanelActions = computed')
    expect(tracking).toContain("promiseTone.value === 'danger'")
    expect(tracking).toContain("actions.unshift(reorderAction.value)")
    expect(tracking).toContain('const hasStatusPanelActions = computed')
    expect(tracking).toContain('const visiblePromiseRows = computed')
    expect(tracking).toContain("'última atualização'")
    expect(tracking).toContain("'sua ação'")
    expect(tracking).toContain('{{ tracking.last_updated_display }}')
    expect(tracking).toContain('Ações disponíveis')
    expect(tracking).toContain('handleStatusPanelAction')
    expect(tracking).toContain('showSupportInStatusPanel')
    expect(tracking).toContain('const showDeliveryTab = computed')
    expect(tracking).toContain("const deliveryTabLabel = computed(() => tracking.value?.is_delivery ? 'Entrega' : 'Retirada')")
    expect(tracking).toContain('const trackingTabsListClass =')
    expect(tracking).toContain('before:bg-border relative h-auto w-full justify-start gap-0.5 overflow-x-auto bg-transparent p-0 before:absolute')
    expect(tracking).toContain('const trackingTabsTriggerClass =')
    expect(tracking).toContain('border-border bg-muted overflow-hidden rounded-b-none border-x border-t py-2 data-[state=active]:z-10')
    expect(tracking).toContain('<UiTabs default-value="history"')
    expect(tracking).toContain('<UiTabsList :pill="false" :class="trackingTabsListClass">')
    expect(tracking).toContain('<UiTabsTrigger :pill="false" value="history" :class="trackingTabsTriggerClass">Histórico</UiTabsTrigger>')
    expect(tracking).toContain('<UiTabsTrigger :pill="false" value="summary" :class="trackingTabsTriggerClass">Resumo</UiTabsTrigger>')
    expect(tracking).toContain('<UiTabsTrigger v-if="showDeliveryTab" :pill="false" value="delivery" :class="trackingTabsTriggerClass">{{ deliveryTabLabel }}</UiTabsTrigger>')
    expect(tracking).toContain('<UiTabsContent value="history">')
    expect(tracking).toContain('<UiTabsContent value="summary">')
    expect(tracking).toContain('<UiTabsContent v-if="showDeliveryTab" value="delivery">')
    expect(tracking).toContain('Resumo do pedido')
    expect(tracking).toContain('{{ tracking.copy.items_heading }}')
    expect(tracking).toContain('<UiDescriptionList class="rounded-lg border px-3">')
    expect(tracking).toContain('<UiDescriptionListTerm>{{ tracking.copy.total_label }}</UiDescriptionListTerm>')
    expect(tracking).toContain('<UiDescriptionListTerm>Recebimento</UiDescriptionListTerm>')
    expect(tracking).toContain('<UiAlertTitle>Endereço</UiAlertTitle>')
    expect(tracking).not.toContain("tracking.payment_status || 'Não informado'")
    expect(tracking).not.toContain('<UiAlertTitle>{{ tracking.pickup_info.heading }}</UiAlertTitle>')
    expect(tracking).not.toContain('Próximas ações')
    expect(tracking).not.toContain('<UiCardTitle>{{ tracking.copy.progress_heading }}</UiCardTitle>')
    expect(tracking).not.toContain('<UiTabsTrigger value="items">Itens</UiTabsTrigger>')
    expect(tracking).not.toContain('<UiTabsTrigger value="timeline">Timeline</UiTabsTrigger>')
    expect(tracking).not.toContain('value="timeline"')
    expect(tracking).not.toContain('<UiBadge')
    expect(tracking).not.toContain('<UiProgress :model-value="progressPercent"')
    expect(tracking).not.toContain('tracking.promise.next_event || tracking.last_updated_display')
    expect(tracking).not.toContain('<UiCardTitle>Próxima ação</UiCardTitle>')
    expect(tracking).toContain('<UiCardTitle>Ações</UiCardTitle>')
    expect(tracking).toContain('performReorderSafely')
  })

  it('submits coupon payload using the backend contract key', () => {
    const cartState = read('app/composables/useCartState.ts')

    expect(cartState).toContain('{ code: coupon_code }')
    expect(cartState).not.toContain('{ coupon_code }')
  })

  it('keeps the UI Thing theme surface-owned with stone primary and doubled radius', () => {
    const css = read('app/assets/css/tailwind.css')
    const config = read('ui-thing.config.ts')
    const theme = read('app/utils/shopTheme.ts')

    expect(config).toContain('"theme": "stone"')
    expect(css).toContain('--radius: 0.5rem')
    expect(css).toContain('--radius-xl: var(--radius)')
    expect(css).toContain('--primary: oklch(0.374 0.010 67.558)')
    expect(css).toContain('--sidebar-primary: oklch(0.374 0.010 67.558)')
    expect(css).toContain('--destructive-foreground: oklch(0.985 0 0)')
    expect(css).toContain('--font-sans: ui-sans-serif')
    expect(css).not.toContain('"Inter"')
    expect(css).toContain('@apply bg-muted text-foreground')
    expect(css).toContain('@apply min-h-dvh min-w-0 bg-muted text-foreground')
    expect(theme).toContain('--shop-brand-color')
    expect(theme).not.toContain('TOKEN_TO_CSS_VAR')
    expect(theme).not.toContain("style['--primary']")
  })

  it('keeps cart counters on canonical UiBadge without extending the component API', () => {
    const badge = read('app/components/Ui/Badge.vue')
    const header = read('app/components/ShopHeader.vue')
    const bottomNav = read('app/components/AppBottomNav.vue')

    expect(badge).not.toContain('counter:')
    expect(header).not.toContain('<UiBadge')
    expect(header).toContain('`Carrinho (${cart.items_count})`')
    expect(bottomNav).toContain('<UiBadge')
    expect(bottomNav).toContain('size="sm"')
    expect(bottomNav).toContain('rounded-full')
    expect(header).not.toContain('-ml-3 -mt-7')
    expect(bottomNav).not.toContain('class="absolute right-2 top-1 px-1"')
  })

  it('uses canonical guide-line subcomponents for tracking timeline and keeps checkout as progressive sections', () => {
    const tracking = read('app/pages/tracking/[ref].vue')
    const checkout = read('app/pages/checkout.vue')
    const checkoutFlow = read('app/utils/checkoutFlow.ts')

    expect(tracking).toContain('<UiTimeline :model-value="progressTimelineStep"')
    expect(tracking).toContain(':step="index + 1"')
    expect(tracking).toContain('group-data-[orientation=vertical]/timeline:ms-10')
    expect(tracking).toContain('group-data-[orientation=vertical]/timeline:-left-7 group-data-[orientation=vertical]/timeline:h-[calc(100%-1.5rem-0.25rem)] group-data-[orientation=vertical]/timeline:translate-y-6.5')
    expect(tracking).toContain('group-data-completed/timeline-item:bg-primary group-data-completed/timeline-item:text-primary-foreground flex size-6 items-center justify-center group-data-completed/timeline-item:border-none')
    expect(tracking).toContain('name="lucide:check"')
    expect(tracking).toContain('class="group-not-data-completed/timeline-item:hidden"')
    expect(tracking).not.toContain("step.state === 'completed' ? 'bg-primary' : ''")
    expect(checkout).toContain('data-checkout-progress-stack')
    expect(checkout).toContain('stepIcon')
    expect(checkoutFlow).toContain('isCheckoutStepDone')
    expect(checkoutFlow).toContain('isCheckoutStepUpcoming')
    expect(checkout).not.toContain('<UiStepper')
    expect(checkout).not.toContain('hidden flex-1 sm:block')
  })

  it('does not shadow Vue refs in tracking after checkout navigation', () => {
    const tracking = read('app/pages/tracking/[ref].vue')

    expect(tracking).toContain('const orderRef = computed')
    expect(tracking).not.toContain('const ref = computed')
    expect(tracking).toContain('const rating = ref(5)')
  })

  it('prevents dead add-to-cart taps before client hydration', () => {
    const action = read('app/components/CartQuantityAction.vue')

    expect(action).toContain('const hydrated = ref(false)')
    expect(action).toContain('onMounted')
    expect(action).toContain('!hydrated.value')
    expect(action).toContain(':disabled="!hydrated || disabled || pending"')
  })

  it('serves the storefront locally on its reserved dev port at the root path', () => {
    const pkg = JSON.parse(read('package.json'))
    const smoke = read('scripts/ux-smoke.mjs')

    expect(pkg.scripts.dev).toContain('--port 3000')
    expect(smoke).toContain('http://127.0.0.1:3000')
  })

  it('formats simple Portuguese counts without placeholder copy', () => {
    expect(formatCount(1, 'item', 'itens')).toBe('1 item')
    expect(formatCount(2, 'item', 'itens')).toBe('2 itens')
  })
})
