# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmotenashiCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador da cópia (ex: CART_EMPTY, PAYMENT_CONFIRMED).",
                        max_length=64,
                        verbose_name="chave",
                    ),
                ),
                (
                    "moment",
                    models.CharField(
                        default="*",
                        help_text=(
                            'Momento do dia ("manha", "almoco", "tarde", "fechando", "fechado", "madrugada")'
                            ' ou "*" para qualquer.'
                        ),
                        max_length=16,
                        verbose_name="momento",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        default="*",
                        help_text='Perfil da pessoa ("anon", "new", "returning", "vip") ou "*" para qualquer.',
                        max_length=16,
                        verbose_name="público",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120, verbose_name="título")),
                ("message", models.TextField(blank=True, verbose_name="mensagem")),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cópia omotenashi",
                "verbose_name_plural": "cópias omotenashi",
                "ordering": ("key", "moment", "audience"),
                "indexes": [models.Index(fields=["key", "active"], name="shop_omoten_key_0ee9b2_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "moment", "audience"),
                        name="uniq_omotenashi_copy_triplet",
                    ),
                ],
            },
        ),
    ]
