# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_omotenashi_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="conservation_tips_default",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Texto exibido no accordion de conservação do PDP quando o produto "
                    "não tiver dica específica (Product.storage_tip). Cada produto pode "
                    "sobrescrever individualmente."
                ),
                verbose_name="dicas de conservação (padrão)",
            ),
        ),
    ]
