# Generated by Django 5.2.11 on 2026-04-18 22:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_conservation_tips_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOmotenashiCopy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Identificador da cópia (ex: CART_EMPTY, PAYMENT_CONFIRMED).', max_length=64, verbose_name='chave')),
                ('moment', models.CharField(default='*', help_text='Momento do dia ("manha", "almoco", "tarde", "fechando", "fechado", "madrugada") ou "*" para qualquer.', max_length=16, verbose_name='momento')),
                ('audience', models.CharField(default='*', help_text='Perfil da pessoa ("anon", "new", "returning", "vip") ou "*" para qualquer.', max_length=16, verbose_name='público')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='título')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cópia omotenashi',
                'verbose_name_plural': 'historical cópias omotenashi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
