# Generated by Django 5.2.12 on 2026-04-18 22:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_conservation_tips_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleconfig',
            options={'ordering': ['priority'], 'permissions': [('manage_rules', 'Pode gerenciar regras de pricing e validação')], 'verbose_name': 'regra configurável', 'verbose_name_plural': 'regras configuráveis'},
        ),
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação')], max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='rule_path',
            field=models.CharField(help_text='Dotted path to the rule class (e.g. shopman.shop.rules.pricing.D1Rule)', max_length=200, verbose_name='caminho da regra'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='body_font',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Instrument Sans', 'Instrument Sans'), ('DM Sans', 'DM Sans'), ('Work Sans', 'Work Sans'), ('Plus Jakarta Sans', 'Plus Jakarta Sans'), ('Nunito Sans', 'Nunito Sans'), ('Source Sans 3', 'Source Sans 3'), ('Outfit', 'Outfit'), ('Raleway', 'Raleway'), ('Rubik', 'Rubik'), ('Manrope', 'Manrope')], default='Inter', max_length=100, verbose_name='fonte de corpo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='heading_font',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Instrument Sans', 'Instrument Sans'), ('Playfair Display', 'Playfair Display'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('EB Garamond', 'EB Garamond'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Serif Display', 'DM Serif Display'), ('Fraunces', 'Fraunces'), ('Bitter', 'Bitter'), ('Crimson Pro', 'Crimson Pro')], default='Inter', max_length=100, verbose_name='fonte de títulos'),
        ),
        migrations.CreateModel(
            name='HistoricalRuleConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, verbose_name='código')),
                ('rule_path', models.CharField(help_text='Dotted path to the rule class (e.g. shopman.shop.rules.pricing.D1Rule)', max_length=200, verbose_name='caminho da regra')),
                ('label', models.CharField(max_length=120, verbose_name='nome exibido')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Parâmetros da regra (ex: percentual, horários, SKUs)', verbose_name='parâmetros')),
                ('priority', models.IntegerField(default=0, help_text='Regras com menor número são avaliadas primeiro', verbose_name='prioridade')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical regra configurável',
                'verbose_name_plural': 'historical regras configuráveis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
