# Generated by Django 5.2.12 on 2026-04-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_omotenashicopy_history'),
        ('shop', '0005_rules_managers_group'),
    ]

    operations = [
    ]
