# Generated by Django 5.2.11 on 2026-04-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_0004_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregistersession',
            options={'ordering': ['-opened_at'], 'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)')], 'verbose_name': 'Sessão de Caixa', 'verbose_name_plural': 'Sessões de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='dayclosing',
            options={'ordering': ['-date'], 'permissions': [('perform_closing', 'Pode executar fechamento do dia')], 'verbose_name': 'fechamento do dia', 'verbose_name_plural': 'fechamentos do dia'},
        ),
        migrations.AlterModelOptions(
            name='kdsticket',
            options={'ordering': ['created_at'], 'permissions': [('operate_kds', 'Pode operar telas KDS (check, done, expedition)')], 'verbose_name': 'ticket KDS', 'verbose_name_plural': 'tickets KDS'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': [('manage_orders', 'Pode confirmar/rejeitar/avançar/cancelar pedidos'), ('manage_production', 'Pode criar WorkOrders e avançar produção'), ('manage_catalog', 'Pode criar/editar Product, Listing e Collection'), ('manage_customers', 'Pode criar/editar Customer, grupos e loyalty'), ('view_reports', 'Pode acessar dashboard e relatórios analíticos')], 'verbose_name': 'loja', 'verbose_name_plural': 'loja'},
        ),
    ]
