# Generated by Django 5.2.12 on 2026-04-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20260418_2021'),
        ('shop', '0008_setup_default_groups'),
    ]

    operations = [
    ]
