# Generated by Django 5.2.11 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_merge_20260420_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovement',
            name='session',
        ),
        migrations.RemoveField(
            model_name='cashregistersession',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='dayclosing',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='kdsinstance',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='kdsticket',
            name='kds_instance',
        ),
        migrations.RemoveField(
            model_name='kdsticket',
            name='order',
        ),
        migrations.DeleteModel(
            name='OperatorAlert',
        ),
        migrations.AlterField(
            model_name='channel',
            name='ref',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='código'),
        ),
        migrations.DeleteModel(
            name='CashMovement',
        ),
        migrations.DeleteModel(
            name='CashRegisterSession',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='DayClosing',
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
        migrations.DeleteModel(
            name='KDSInstance',
        ),
        migrations.DeleteModel(
            name='KDSTicket',
        ),
    ]
