# Generated by Django 5.2.11 on 2026-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cashmovement_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(default='base', help_text='Tipo comportamental do canal. O comportamento operacional é resolvido por ChannelConfig, sem classes de Flow.', max_length=32, verbose_name='tipo'),
        ),
    ]
