# Generated by Django 5.2.11 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_cashmovement_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="food_safety_notice",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Aviso exibido na seção de ingredientes do PDP quando a operação "
                    "usa cozinha compartilhada ou tem risco de traços."
                ),
                verbose_name="aviso de produção compartilhada",
            ),
        ),
    ]
