# Generated by Codex on 2026-04-27

from django.db import migrations


SHOP_PERMISSIONS = [
    ("manage_orders", "Pode confirmar/rejeitar/avançar/cancelar pedidos"),
    ("manage_production", "Pode criar WorkOrders e avançar produção"),
    ("view_production_suggested", "Pode ver sugestão de produção"),
    ("edit_production_suggested", "Pode transformar sugestão em planejamento"),
    ("view_production_planned", "Pode ver produção planejada"),
    ("edit_production_planned", "Pode editar produção planejada"),
    ("view_production_started", "Pode ver produção iniciada"),
    ("edit_production_started", "Pode informar entrada em produção"),
    ("view_production_finished", "Pode ver produção concluída"),
    ("edit_production_finished", "Pode informar produção concluída"),
    ("view_production_unsold", "Pode ver não vendidos da produção"),
    ("edit_production_unsold", "Pode informar não vendidos da produção"),
    ("manage_catalog", "Pode criar/editar Product, Listing e Collection"),
    ("manage_customers", "Pode criar/editar Customer, grupos e loyalty"),
    ("view_reports", "Pode acessar dashboard e relatórios analíticos"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_shop_food_safety_notice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={
                "verbose_name": "loja",
                "verbose_name_plural": "loja",
                "permissions": SHOP_PERMISSIONS,
            },
        ),
    ]
