# Generated by Django 5.2.11 on 2026-06-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cleanup_orphan_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAppearance',
            fields=[
            ],
            options={
                'verbose_name': 'Marca e aparência',
                'verbose_name_plural': 'Marca e aparência',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopIntegrations',
            fields=[
            ],
            options={
                'verbose_name': 'Integrações',
                'verbose_name_plural': 'Integrações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopLoyalty',
            fields=[
            ],
            options={
                'verbose_name': 'Fidelidade',
                'verbose_name_plural': 'Fidelidade',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopMenu',
            fields=[
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápio',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopOperation',
            fields=[
            ],
            options={
                'verbose_name': 'Horários e operação',
                'verbose_name_plural': 'Horários e operação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopOrdering',
            fields=[
            ],
            options={
                'verbose_name': 'Pedidos e entrega',
                'verbose_name_plural': 'Pedidos e entrega',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopPos',
            fields=[
            ],
            options={
                'verbose_name': 'PDV e alertas',
                'verbose_name_plural': 'PDV e alertas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.CreateModel(
            name='ShopProduction',
            fields=[
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produção',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
    ]
