# Generated by Django 6.0.5 on 2026-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_shopappearance_shopintegrations_shoployalty_shopmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='whatsapp_flow_ns',
            field=models.CharField(blank=True, help_text="Namespace do flow no ManyChat p/ este evento (ex: content20250401120000_123456). Vazio = envia a 'mensagem' como texto direto.", max_length=120, verbose_name='flow do WhatsApp (ManyChat)'),
        ),
    ]
