# Generated by Django 6.0.5 on 2026-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_notificationtemplate_whatsapp_flow_ns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=64, unique=True, verbose_name='referência')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('kind', models.CharField(choices=[('menuboard', '📺 Menuboard (TV na loja)'), ('google', '🛰 Feed Google'), ('meta', '🛰 Feed Meta')], default='menuboard', max_length=20, verbose_name='tipo')),
                ('collections', models.JSONField(blank=True, default=list, verbose_name='coleções')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='opções')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
                'ordering': ('name',),
            },
        ),
    ]
