# Generated by Django 6.0.5 on 2026-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cancellation_presets',
            field=models.JSONField(blank=True, default=list, help_text='Justificativas padrão que o operador injeta com um toque ao recusar ou cancelar um pedido no gestor. O texto escolhido é enviado ao cliente na notificação, então escreva na voz da loja.\nExemplo:\n[\n  "Item indisponível no momento",\n  "Sem um dos ingredientes hoje",\n  "Problema técnico no preparo"\n]', verbose_name='motivos de cancelamento/recusa'),
        ),
    ]
