# Generated by Django 6.0.6 on 2026-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_shop_cancellation_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='kitchen_note_tags',
            field=models.JSONField(blank=True, default=list, help_text='Etiquetas prontas que o operador anexa com um toque à nota da cozinha de um pedido no gestor. A nota (tags + texto livre) é exibida no ticket do KDS para a produção. Escreva instruções curtas de preparo.\nExemplo:\n[\n  "Bem assado",\n  "Sem cebola",\n  "Embalar para presente",\n  "Cortar ao meio"\n]', verbose_name='tags de nota da cozinha'),
        ),
    ]
