# Generated by Django 6.0.5 on 2026-07-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_ruleconfig_code_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['event'], 'verbose_name': 'modelo de mensagem', 'verbose_name_plural': 'modelos de mensagem'},
        ),
    ]
