# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_notificationtemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalomotenashicopy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical texto da interface', 'verbose_name_plural': 'historical textos da interface'},
        ),
        migrations.AlterModelOptions(
            name='historicalruleconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical regra', 'verbose_name_plural': 'historical regras'},
        ),
        migrations.AlterModelOptions(
            name='omotenashicopy',
            options={'ordering': ('key', 'moment', 'audience'), 'verbose_name': 'texto da interface', 'verbose_name_plural': 'textos da interface'},
        ),
        migrations.AlterModelOptions(
            name='ruleconfig',
            options={'ordering': ['priority'], 'permissions': [('manage_rules', 'Pode gerenciar regras de pricing e validação')], 'verbose_name': 'regra', 'verbose_name_plural': 'regras'},
        ),
    ]
