# Generated by Django 6.0.7 on 2026-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_historicalomotenashicopy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('platform', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('error', 'Erro'), ('retracted', 'Retirado'), ('skipped', 'Ignorado')], default='pending', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estado de sync do catálogo',
                'verbose_name_plural': 'estados de sync do catálogo',
                'indexes': [models.Index(fields=['platform', 'status'], name='shop_catalo_platfor_1894f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('sku', 'platform'), name='uniq_catalog_sync_sku_platform')],
            },
        ),
    ]
