# Generated by Django 6.0.5 on 2026-07-18 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_catalogsyncstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('body', models.TextField(help_text='Use {{produto}}, {{preco}}, {{hashtags}}, {{link}}, {{loja}}…', verbose_name='corpo')),
                ('platform_variants', models.JSONField(blank=True, default=dict, help_text='Override por plataforma, ex: {"google_business": {"body": "…"}}', verbose_name='variações por plataforma')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Variáveis que este template espera (documentação para o gestor)', verbose_name='variáveis')),
                ('use_ai_generation', models.BooleanField(default=False, help_text='Quando ligado, a IA escreve a partir do contexto do evento', verbose_name='gerar texto com IA')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='instrução para a IA')),
                ('image_source', models.CharField(choices=[('product', 'foto do produto'), ('gallery', 'galeria do produto'), ('custom', 'imagem fixa'), ('none', 'sem imagem')], default='product', max_length=16, verbose_name='origem da imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modelo de post',
                'verbose_name_plural': 'modelos de post',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('trigger', models.CharField(choices=[('production_finished', 'fornada concluída'), ('low_stock', 'estoque baixo'), ('stock_back', 'voltou ao estoque'), ('product_created', 'produto novo'), ('scheduled', 'agendado')], max_length=64, verbose_name='gatilho')),
                ('trigger_filter', models.JSONField(blank=True, default=dict, help_text='Condições extras, ex: {"collections": ["paes"], "quality_min": "bom"}', verbose_name='filtro do gatilho')),
                ('platforms', models.JSONField(default=list, help_text='["instagram", "google_business", "facebook", "whatsapp", "tv"]', verbose_name='plataformas')),
                ('audience_rules', models.JSONField(blank=True, default=dict, help_text='{"favorites": true, "alerts": true, "recompra_days": 90, "vip_first_minutes": 15}', verbose_name='regras de audiência')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='{"type": "immediate"} ou {"type": "cron", "expr": "0 7 * * *"}', verbose_name='agendamento')),
                ('requires_approval', models.BooleanField(default=True, help_text='Desligado = publica sozinho, sem o gestor revisar', verbose_name='exige aprovação')),
                ('expires_after_minutes', models.PositiveIntegerField(default=0, help_text='Post não aprovado caduca depois disso. 0 = não expira. Frescor é efêmero: fornada merece prazo curto.', verbose_name='expira em (min)')),
                ('notify_users', models.JSONField(blank=True, default=list, help_text='IDs de usuário a notificar. Vazio = todos com a permissão de gerenciar broadcast.', verbose_name='avisar usuários')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='shop.posttemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'regra de broadcast',
                'verbose_name_plural': 'regras de broadcast',
                'ordering': ['name'],
                'permissions': [('manage_broadcast', 'Pode revisar e publicar posts de broadcast')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'rascunho'), ('pending_review', 'aguardando aprovação'), ('approved', 'aprovado'), ('publishing', 'publicando'), ('published', 'publicado'), ('failed', 'falhou'), ('expired', 'expirado')], default='draft', max_length=16, verbose_name='situação')),
                ('content', models.JSONField(default=dict, help_text='{"body": "…", "image_url": "…", "hashtags": [...], "link": "…"}', verbose_name='conteúdo')),
                ('platform_content', models.JSONField(blank=True, default=dict, verbose_name='conteúdo por plataforma')),
                ('platforms', models.JSONField(blank=True, default=list, verbose_name='plataformas')),
                ('audience', models.JSONField(blank=True, default=dict, help_text='Só contagens — a lista de destinatários nunca é persistida aqui', verbose_name='audiência')),
                ('platform_results', models.JSONField(blank=True, default=dict, verbose_name='resultado por plataforma')),
                ('trigger_context', models.JSONField(blank=True, default=dict, verbose_name='contexto do evento')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_broadcast_posts', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='shop.broadcastrule', verbose_name='regra')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='shop.posttemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'post de broadcast',
                'verbose_name_plural': 'posts de broadcast',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('broadcast', 'broadcast'), ('production', 'produção'), ('order', 'pedidos'), ('system', 'sistema')], default='system', max_length=32, verbose_name='categoria')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('action_url', models.CharField(blank=True, help_text='Deep link relativo dentro das superfícies de operador', max_length=500, verbose_name='link')),
                ('action_data', models.JSONField(blank=True, default=dict, help_text='Payload da ação, ex: {"broadcast_post_id": 12}', verbose_name='dados da ação')),
                ('is_actionable', models.BooleanField(default=False, help_text='A notificação pede uma decisão, não só informa', verbose_name='acionável')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='broadcastrule',
            index=models.Index(fields=['trigger', 'is_active'], name='shop_broadc_trigger_a01f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastpost',
            index=models.Index(fields=['status', '-created_at'], name='shop_broadc_status_21e56f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastpost',
            index=models.Index(fields=['expires_at'], name='shop_broadc_expires_a3fe63_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='shop_userno_user_id_d12c85_idx'),
        ),
    ]
