# Generated by Django 6.0.5 on 2026-07-18 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_posttemplate_broadcastrule_broadcastpost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastpost',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Aprovado com hora marcada. Preenchido = ainda não saiu; volta a vazio no despacho.', null=True, verbose_name='publicar em'),
        ),
        migrations.AddIndex(
            model_name='broadcastpost',
            index=models.Index(fields=['publish_at'], name='shop_broadc_publish_ebcbc7_idx'),
        ),
    ]
