# Generated by Django 5.2.11 on 2026-03-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do cliente. Ex: {"preferences": "sem lactose", "birthday": "1990-05-15"}', verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do grupo. Ex: {"discount_percent": 10, "min_order_q": 5000}', verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Dados do provedor externo. Ex: {"wa_id": "5543...", "ig_scoped_id": "abc123"}', verbose_name='metadados do provedor'),
        ),
        migrations.CreateModel(
            name='CommunicationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], db_index=True, max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('opted_in', 'Opt-in'), ('opted_out', 'Opt-out'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='status')),
                ('legal_basis', models.CharField(choices=[('consent', 'Consentimento'), ('legitimate_interest', 'Interesse legítimo'), ('contract', 'Execução de contrato'), ('legal_obligation', 'Obrigação legal')], default='consent', help_text='Base legal LGPD para o tratamento de dados', max_length=30, verbose_name='base legal')),
                ('source', models.CharField(blank=True, help_text='Como o consentimento foi coletado (checkout, form, whatsapp)', max_length=100, verbose_name='origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP no momento do consentimento', null=True, verbose_name='endereço IP')),
                ('consented_at', models.DateTimeField(blank=True, help_text='Data/hora do opt-in', null=True, verbose_name='consentido em')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Data/hora do opt-out', null=True, verbose_name='revogado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'consentimento de comunicação',
                'verbose_name_plural': 'consentimentos de comunicação',
                'ordering': ['channel'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'channel'), name='customers_unique_consent_per_channel')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order', 'Pedido'), ('contact', 'Contato'), ('note', 'Nota'), ('visit', 'Visita'), ('loyalty', 'Fidelidade'), ('system', 'Sistema')], db_index=True, max_length=20, verbose_name='tipo')),
                ('title', models.CharField(help_text='Resumo curto do evento', max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, help_text='Detalhes adicionais do evento', verbose_name='descrição')),
                ('channel', models.CharField(blank=True, help_text='Canal de origem (whatsapp, pdv, ecommerce, etc.)', max_length=50, verbose_name='canal')),
                ('reference', models.CharField(blank=True, help_text='ID externo (ex: order:123, ticket:456)', max_length=100, verbose_name='referência')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados extras do evento (JSON livre)', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('created_by', models.CharField(blank=True, help_text='Usuário ou sistema que criou o evento', max_length=100, verbose_name='criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'evento da timeline',
                'verbose_name_plural': 'eventos da timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customers_t_custome_9c00da_idx'), models.Index(fields=['customer', 'event_type'], name='customers_t_custome_e6e324_idx')],
            },
        ),
    ]
