# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recipe',
            new_name='crafting_re_output__2febea_idx',
            old_name='crafting_re_output__idx',
        ),
        migrations.RenameIndex(
            model_name='recipe',
            new_name='crafting_re_is_acti_16b7d2_idx',
            old_name='crafting_re_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='crafting_wo_status_9c8483_idx',
            old_name='crafting_wo_status_sched_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='crafting_wo_output__e9dbc2_idx',
            old_name='crafting_wo_output_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='crafting_wo_schedul_173027_idx',
            old_name='crafting_wo_sched_date_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderitem',
            new_name='crafting_wo_work_or_d18282_idx',
            old_name='crafting_wi_wo_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderitem',
            new_name='crafting_wo_item_re_aa0889_idx',
            old_name='crafting_wi_item_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderitem',
            new_name='crafting_wo_recorde_7781b6_idx',
            old_name='crafting_wi_recorded_idx',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados da receita. Ex: {"prep_time_min": 30, "bake_temp_c": 220}', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='Etapas de produção. Ex: ["Mistura", "Fermentação", "Modelagem", "Forno"]', verbose_name='Etapas'),
        ),
        migrations.AlterField(
            model_name='workorderevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Dados do evento. Ex: {"produced": 48, "waste": 2}', verbose_name='Dados'),
        ),
    ]
