# Generated by Django 5.2.11 on 2026-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0003_alter_workorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='finished',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Set no finish, imutavel depois', max_digits=12, null=True, verbose_name='Quantidade Concluída'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('started', 'Iniciada'), ('finished', 'Concluída'), ('void', 'Cancelada')], default='planned', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workorderevent',
            name='kind',
            field=models.CharField(choices=[('planned', 'Planejado'), ('adjusted', 'Ajustado'), ('started', 'Iniciado'), ('finished', 'Concluído'), ('voided', 'Cancelado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
