# Generated by Django 5.2.11 on 2026-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0004_standardize_production_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('un', 'un.'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('L', 'L'), ('ml', 'ml')], default='kg', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['un', 'kg', 'g', 'mg', 'L', 'ml'])), name='craft_recipeitem_unit_known'),
        ),
    ]
