# Generated by Django 5.2.11 on 2026-04-30 13:05

from django.db import migrations, models
from django.db.models import Count


def ensure_no_duplicate_active_recipe_outputs(apps, schema_editor):
    Recipe = apps.get_model("craftsman", "Recipe")
    duplicates = list(
        Recipe.objects.filter(is_active=True)
        .exclude(output_sku="")
        .values("output_sku")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .order_by("output_sku")
    )
    if not duplicates:
        return
    formatted = ", ".join(f"{item['output_sku']} ({item['count']})" for item in duplicates[:10])
    if len(duplicates) > 10:
        formatted = f"{formatted}, ..."
    raise RuntimeError(
        "Cannot enforce one active Recipe per output_sku. "
        f"Deactivate or merge duplicate active recipes first: {formatted}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0005_alter_recipeitem_unit_and_more'),
    ]

    operations = [
        migrations.RunPython(
            ensure_no_duplicate_active_recipe_outputs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('output_sku', ''), _negated=True)), fields=('output_sku',), name='craft_recipe_active_output_uq'),
        ),
    ]
