# Generated by Django 5.2.11 on 2026-04-30 13:36

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0006_recipe_craft_recipe_active_output_uq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='batch_size',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Quantidade produzida pela ficha técnica base; usada para escalar insumos.', max_digits=12, verbose_name='Rendimento base'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade para o rendimento base da receita.', max_digits=12, verbose_name='Quantidade'),
        ),
    ]
