# Generated by Django 5.2.11 on 2026-04-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0007_rename_batch_size_to_base_yield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Ficha técnica', 'verbose_name_plural': 'Fichas técnicas'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados da ficha técnica. Ex: {"prep_time_min": 30, "bake_temp_c": 220}', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='output_sku',
            field=models.CharField(db_index=True, help_text='SKU ao qual esta ficha técnica/BOM se aplica.', max_length=100, verbose_name='SKU produzido'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade para o rendimento base da ficha técnica.', max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.recipe', verbose_name='Ficha técnica'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='craftsman.recipe', verbose_name='Ficha técnica'),
        ),
    ]
