# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0008_rename_recipe_to_technical_sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'ficha técnica', 'verbose_name_plural': 'fichas técnicas'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'ingrediente', 'verbose_name_plural': 'ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='refsequence',
            options={'verbose_name': 'sequência de referência', 'verbose_name_plural': 'sequências de referência'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'ordem de produção', 'verbose_name_plural': 'ordens de produção'},
        ),
        migrations.AlterModelOptions(
            name='workorderevent',
            options={'ordering': ['work_order', 'seq'], 'verbose_name': 'evento da ordem', 'verbose_name_plural': 'eventos da ordem'},
        ),
        migrations.AlterModelOptions(
            name='workorderitem',
            options={'verbose_name': 'item da ordem', 'verbose_name_plural': 'itens da ordem'},
        ),
    ]
