# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do movimento. Ex: {"reason_detail": "Ajuste de inventário"}', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='position',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados da posição. Ex: {"temperature": "ambiente", "capacity": 500}', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='quant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do quant. Ex: {"batch": "2024-01", "supplier": "Moinho SP"}', verbose_name='Metadados'),
        ),
    ]
