# Generated by Django 6.0.5 on 2026-06-27 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0002_hold_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='kind',
            field=models.CharField(choices=[('make', 'Produção'), ('buy', 'Compra'), ('sell', 'Venda'), ('adjust', 'Ajuste'), ('transfer', 'Transferência'), ('return', 'Devolução'), ('waste', 'Perda/Descarte')], db_index=True, default='adjust', help_text='Evento econômico: produção, compra, venda, ajuste, transferência, devolução, perda/descarte.', max_length=12, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='move',
            name='reason',
            field=models.CharField(help_text='Detalhe livre. Ex: "Produção manhã", "Compra PO-001"', max_length=255, verbose_name='Motivo'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['kind', 'timestamp'], name='stockman_mo_kind_c3d4bd_idx'),
        ),
    ]
