# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0003_move_kind_alter_move_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date', 'production_date'], 'verbose_name': 'lote', 'verbose_name_plural': 'lotes'},
        ),
        migrations.AlterModelOptions(
            name='hold',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['timestamp'], 'verbose_name': 'movimento', 'verbose_name_plural': 'movimentos'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['ref'], 'verbose_name': 'posição', 'verbose_name_plural': 'posições'},
        ),
        migrations.AlterModelOptions(
            name='quant',
            options={'verbose_name': 'saldo', 'verbose_name_plural': 'saldos'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'verbose_name': 'alerta de estoque', 'verbose_name_plural': 'alertas de estoque'},
        ),
    ]
