# Generated by Django 6.0.5 on 2026-06-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0004_backfill_move_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='kind',
            field=models.CharField(choices=[('make', 'Produção'), ('buy', 'Compra'), ('sell', 'Venda'), ('adjust', 'Ajuste'), ('transfer', 'Transferência'), ('return', 'Devolução'), ('waste', 'Perda/Descarte')], db_index=True, default='adjust', help_text='Evento econômico: produção, compra, venda, ajuste, transferência, devolução.', max_length=12, verbose_name='Tipo'),
        ),
    ]
