// Order contract types. The structural shapes come from the generated mirror
// (app/generated/ordersContract.ts — source of truth:
// shopman/backstage/projections/order_queue.py, regenerated by
// `python manage.py export_orders_schema` and drift-guarded in the Django CI).
// This module only narrows fields the backend types as plain `str` and adds
// the API envelopes.

import type {
  OperatorOrderProjection as OperatorOrderContract,
  OrderCardProjection as OrderCardContract,
  TwoZoneQueueProjection as TwoZoneQueueContract,
} from "~/generated/ordersContract";

export type {
  AwaitingWorkOrderProjection,
  OrderItemProjection,
  TimelineEventProjection,
} from "~/generated/ordersContract";

export type OrderTimerClass = "timer-ok" | "timer-warning" | "timer-urgent" | "timer-muted";

export interface OrderCardProjection extends OrderCardContract {
  timer_class: OrderTimerClass;
  fulfillment_type: "delivery" | "pickup";
}

/** A coded cancellation reason (marketplace/iFood requires one per order). */
export interface CancellationReason {
  code: string;
  description: string;
}

/** Courier ride block (Order.data["courier"] → projections._courier_block).
 * `status` is the raw Machine letter (D/G/P/A/S/E/F/N/C/U); labels come from
 * the server, steps/tone are derived client-side (presentation/courier.ts).
 * The backend projection builds this as an untyped dict, so the shape is
 * declared here (as a type alias, assignable to the generated Record). */
export type CourierBlock = {
  provider: string;
  status: string;
  status_label: string;
  active: boolean;
  driver: { name: string; phone: string; vehicle_plate: string; vehicle_model: string } | null;
  tracking_url: string;
  confirmation_code: string;
  estimate_display: string;
  final_value_display: string;
  requested_at: string;
  dispatched_at: string;
  finished_at: string;
  attempts_count: number;
  position: { lat: string; lng: string } | null;
  error: { message: string; at: string } | null;
  can_quote: boolean;
  can_dispatch: boolean;
  can_cancel: boolean;
};

export interface OperatorOrderProjection extends OperatorOrderContract {
  courier: CourierBlock | null;
}

export interface TwoZoneQueueProjection extends TwoZoneQueueContract {
  intake: OrderCardProjection[];
  prep: OrderCardProjection[];
  expedition_pickup: OrderCardProjection[];
  expedition_delivery: OrderCardProjection[];
  expedition_delivery_transit: OrderCardProjection[];
}

export interface OrderQueueResponse {
  queue: TwoZoneQueueProjection;
}

export interface OrderDetailResponse {
  order: OperatorOrderProjection;
}

export interface AlertProjection {
  pk: number;
  type: string;
  type_label: string;
  severity: "warning" | "error" | "critical";
  severity_label: string;
  message: string;
  order_ref: string;
  created_at_display: string;
}

export interface AlertsResponse {
  alerts: AlertProjection[];
  counts: { active: number; critical: number };
}
