# Generated by Django 5.2.12 on 2026-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_session_origin_channel_order_origin_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processing_at',
            new_name='preparing_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'novo'), ('confirmed', 'confirmado'), ('preparing', 'em preparo'), ('ready', 'pronto'), ('dispatched', 'despachado'), ('delivered', 'entregue'), ('completed', 'concluído'), ('cancelled', 'cancelado'), ('returned', 'devolvido')], db_index=True, default='new', max_length=32, verbose_name='status'),
        ),
        # Data migration: update existing rows from "processing" → "preparing"
        migrations.RunSQL(
            sql="UPDATE ordering_order SET status = 'preparing' WHERE status = 'processing';",
            reverse_sql="UPDATE ordering_order SET status = 'processing' WHERE status = 'preparing';",
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE ordering_orderevent "
                "SET payload = jsonb_set(payload, '{new_status}', '\"preparing\"') "
                "WHERE payload->>'new_status' = 'processing';"
            ),
            reverse_sql=(
                "UPDATE ordering_orderevent "
                "SET payload = jsonb_set(payload, '{new_status}', '\"processing\"') "
                "WHERE payload->>'new_status' = 'preparing';"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE ordering_orderevent "
                "SET payload = jsonb_set(payload, '{old_status}', '\"preparing\"') "
                "WHERE payload->>'old_status' = 'processing';"
            ),
            reverse_sql=(
                "UPDATE ordering_orderevent "
                "SET payload = jsonb_set(payload, '{old_status}', '\"processing\"') "
                "WHERE payload->>'old_status' = 'preparing';"
            ),
        ),
    ]
