// Production contract types. The structural shapes come from the generated
// mirror (app/generated/productionContract.ts — source of truth:
// shopman/backstage/projections/production.py, regenerated by
// `python manage.py export_production_schema` and drift-guarded in the Django
// CI). This module only narrows fields the backend types as plain `str`,
// keeps the surface's short aliases, and adds the API envelopes.

import type {
  ForecastRowProjection as ForecastRowContract,
  ProductionBoardProjection,
  ProductionForecastProjection as ProductionForecastContract,
  ProductionKDSCardProjection as ProductionKDSCardContract,
  ProductionKDSProjection as ProductionKDSContract,
  ProductionMiseEnPlaceProjection,
  ProductionWeighingIngredientProjection,
  ProductionWeighingProjection,
  ProductionWeighingTicketProjection,
} from "~/generated/productionContract";

export type {
  BaseRecipeOptionProjection,
  BaseRecipeUsageProjection,
  MiseEnPlaceBreakdownProjection,
  MiseEnPlaceLineProjection,
  OrderCommitmentProjection,
  PositionOptionProjection,
  ProductionBoardProjection,
  ProductionCountsProjection,
  ProductionMatrixGroupProjection,
  ProductionMatrixGroupRowProjection,
  ProductionMatrixRowProjection,
  ProductionMiseEnPlaceProjection,
  ProductionSuggestionProjection,
  ProductionSurfaceAccess,
  ProductionWeighingProjection,
  RecipeOptionProjection,
  WorkOrderCardProjection,
} from "~/generated/productionContract";

export type ProductionTimerClass = "timer-ok" | "timer-warning" | "timer-late";

// ── Live floor (KDS) ───────────────────────────────────────────────────────

export interface ProductionKDSCardProjection extends ProductionKDSCardContract {
  timer_class: ProductionTimerClass;
}

export interface ProductionKDSProjection extends ProductionKDSContract {
  cards: ProductionKDSCardProjection[];
}

export interface ProductionKDSResponse {
  kds: ProductionKDSProjection;
}

// ── Planning board (matrix) ────────────────────────────────────────────────

export interface ProductionBoardResponse {
  board: ProductionBoardProjection;
}

// ── O PAINEL — previsão da produção (estilo aeroporto) ──────────────────────
// O status É a escada de confiança: Planejado → Previsto → Confirmado.

export type ForecastStatus = "scheduled" | "in_progress" | "delayed" | "arrived";

export interface ForecastRowProjection extends ForecastRowContract {
  status: ForecastStatus;
}

export interface ProductionForecastProjection extends ProductionForecastContract {
  rows: ForecastRowProjection[];
}

export interface ProductionForecastResponse {
  forecast: ProductionForecastProjection;
}

// ── Structured shortage envelope (material/order) ──────────────────────────
// Mirrors backstage/api/operations.py `_shortage_response` (HTTP 409).

export interface MaterialShortageItem {
  sku: string;
  needed: string;
  available: string;
  shortage: string;
}

export interface MaterialShortageError {
  code: "material_shortage";
  work_order_ref: string;
  missing: MaterialShortageItem[];
}

export interface OrderShortageError {
  code: "order_shortage";
  work_order_ref: string;
  required: string;
  requested: string;
  order_refs: string[];
}

export type ProductionShortageError = MaterialShortageError | OrderShortageError;

// ── Operator alerts (shared backstage projection) ──────────────────────────

export interface AlertProjection {
  pk: number;
  type: string;
  type_label: string;
  severity: "warning" | "error" | "critical";
  severity_label: string;
  message: string;
  order_ref: string;
  created_at_display: string;
}

export interface AlertsResponse {
  alerts: AlertProjection[];
  counts: { active: number; critical: number };
}

// ── Mise en place (aggregated material needs) ───────────────────────────────

export interface MiseEnPlaceResponse {
  mise_en_place: ProductionMiseEnPlaceProjection;
}

// ── Weighing (per-prep tickets + blind codes) ───────────────────────────────
// Short aliases kept for the surface's components.

export type WeighingIngredientProjection = ProductionWeighingIngredientProjection;
export type WeighingTicketProjection = ProductionWeighingTicketProjection;

export interface WeighingResponse {
  weighing: ProductionWeighingProjection;
}
