# Generated by Django 5.2.11 on 2026-03-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='razão social')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('default_ddd', models.CharField(default='11', max_length=4, verbose_name='DDD padrão')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='fuso horário')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='horários')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='nome curto (PWA)')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='tagline')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('primary_color', models.CharField(default='#9E833E', max_length=7, verbose_name='cor primária')),
                ('background_color', models.CharField(default='#F5F0EB', max_length=7, verbose_name='cor de fundo')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Mesmo schema do ChannelConfig. Canais herdam se não sobreescreverem.', verbose_name='configurações padrão')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'loja',
            },
        ),
    ]
