# Generated by Django 5.2.11 on 2026-03-25 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], max_length=10, verbose_name='tipo')),
                ('value', models.IntegerField(help_text='Percentual (0-100) ou valor fixo em centavos', verbose_name='valor')),
                ('valid_from', models.DateTimeField(verbose_name='válido de')),
                ('valid_until', models.DateTimeField(verbose_name='válido até')),
                ('skus', models.JSONField(blank=True, default=list, help_text='SKUs afetados (vazio = todos)', verbose_name='SKUs')),
                ('collections', models.JSONField(blank=True, default=list, help_text='Collection refs afetados (vazio = todos)', verbose_name='coleções')),
                ('min_order_q', models.IntegerField(default=0, help_text='Valor mínimo do pedido em centavos (0 = sem mínimo)', verbose_name='pedido mínimo (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='código')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='usos máximos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shop.promotion', verbose_name='promoção')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
    ]
