# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promotion_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='collections',
            field=models.JSONField(blank=True, default=list, help_text='Collection refs afetados (vazio = todos). Ex: ["paes-artesanais", "confeitaria"]', verbose_name='coleções'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='skus',
            field=models.JSONField(blank=True, default=list, help_text='SKUs afetados (vazio = todos). Ex: ["PAO-FRANCES", "CROISSANT"]', verbose_name='SKUs'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horários por dia da semana. Exemplo: {"monday": {"open": "06:00", "close": "20:00"}, "tuesday": {"open": "06:00", "close": "20:00"}, ...}. Dias: monday, tuesday, wednesday, thursday, friday, saturday, sunday.', verbose_name='horários'),
        ),
    ]
