# Generated by Django 5.2.11 on 2026-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_promotion_collections_alter_promotion_skus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs das redes sociais. Exemplo:\n[\n  "https://wa.me/554333231997",\n  "https://instagram.com/nelsonboulangerie",\n  "https://www.facebook.com/nelsonboulangerie",\n  "https://www.tiktok.com/@nelsonboulangerie",\n  "https://www.youtube.com/@nelsonboulangerie",\n  "https://twitter.com/nelsonboulangerie",\n  "https://www.nelsonboulangerie.com.br"\n]\nPlataformas reconhecidas: WhatsApp, Instagram, Facebook, TikTok, YouTube, X/Twitter, LinkedIn, Telegram, Pinterest. Qualquer outra URL aparece como ícone de link genérico.', verbose_name='redes sociais'),
        ),
    ]
