# Generated by Django 5.2.11 on 2026-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='state',
        ),
        migrations.AddField(
            model_name='shop',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country_code',
            field=models.CharField(default='BR', max_length=5, verbose_name='código do país'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='shop',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Endereço formatado completo (ex: Av. Madre Leônia Milito, 446 - Bela Suíça, Londrina - PR, 86050-270)', max_length=500, verbose_name='endereço completo'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='shop',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='shop',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='shop',
            name='route',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='shop',
            name='state_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
    ]
