# Generated by Django 5.2.11 on 2026-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_google_maps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='fulfillment_types',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de entrega (vazio = todos). Ex: ["delivery", "pickup"]', verbose_name='tipos de entrega'),
        ),
    ]
