# Generated by Django 5.2.11 on 2026-03-27 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_fulfillment_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('data', models.JSONField(blank=True, default=list, help_text='Lista de dicts: [{sku, qty_remaining, qty_d1, qty_loss}]', verbose_name='snapshot')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento do dia',
                'verbose_name_plural': 'fechamentos do dia',
                'ordering': ['-date'],
            },
        ),
    ]
