# Generated by Django 5.2.11 on 2026-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_day_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='customer_segments',
            field=models.JSONField(blank=True, default=list, help_text='Segmentos RFM para targeting (vazio = todos). Ex: ["champions", "loyal"]', verbose_name='segmentos de cliente'),
        ),
    ]
