# Generated by Django 5.2.11 on 2026-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='body_font',
            field=models.CharField(default='Inter', help_text='Nome da fonte Google Fonts para texto (ex: Inter, DM Sans, Work Sans)', max_length=100, verbose_name='fonte de corpo'),
        ),
        migrations.AddField(
            model_name='shop',
            name='border_color',
            field=models.CharField(blank=True, default='#E8E0D8', max_length=9, verbose_name='cor de bordas'),
        ),
        migrations.AddField(
            model_name='shop',
            name='border_radius',
            field=models.CharField(choices=[('sharp', 'Reto (2px)'), ('default', 'Padrão (6px)'), ('relaxed', 'Suave (12px)'), ('rounded', 'Arredondado (16px)'), ('pill', 'Pílula (9999px)')], default='relaxed', help_text='Define o arredondamento dos cantos de botões, cards e inputs', max_length=20, verbose_name='arredondamento'),
        ),
        migrations.AddField(
            model_name='shop',
            name='heading_font',
            field=models.CharField(default='Playfair Display', help_text='Nome da fonte Google Fonts para títulos (ex: Playfair Display, Cormorant, Lora)', max_length=100, verbose_name='fonte de títulos'),
        ),
        migrations.AddField(
            model_name='shop',
            name='surface_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=9, verbose_name='cor de cards/superfícies'),
        ),
        migrations.AddField(
            model_name='shop',
            name='text_color',
            field=models.CharField(blank=True, default='#3D2B1F', max_length=9, verbose_name='cor de texto'),
        ),
        migrations.AddField(
            model_name='shop',
            name='text_muted_color',
            field=models.CharField(blank=True, default='#6B5E57', max_length=9, verbose_name='cor de texto secundário'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='background_color',
            field=models.CharField(default='#F5F0EB', max_length=9, verbose_name='cor de fundo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='primary_color',
            field=models.CharField(default='#9E833E', max_length=9, verbose_name='cor primária'),
        ),
    ]
