# Generated by Django 5.2.11 on 2026-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_design_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='surface_color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='text_muted_color',
        ),
        migrations.AddField(
            model_name='shop',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Cor de destaque/CTA. Vazio = derivada automaticamente (hue -60° da primária)', max_length=9, verbose_name='cor de destaque'),
        ),
        migrations.AddField(
            model_name='shop',
            name='color_mode',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático (sistema do usuário)')], default='light', help_text='Automático respeita a preferência de tema do sistema do usuário', max_length=10, verbose_name='modo de cor'),
        ),
        migrations.AddField(
            model_name='shop',
            name='neutral_color',
            field=models.CharField(blank=True, default='', help_text='Tom para textos e bordas. Vazio = primária dessaturada', max_length=9, verbose_name='tom neutro'),
        ),
        migrations.AddField(
            model_name='shop',
            name='secondary_color',
            field=models.CharField(blank=True, default='', help_text='Cor de apoio. Vazio = derivada automaticamente (hue +120° da primária)', max_length=9, verbose_name='cor secundária'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='website',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='whatsapp',
        ),
    ]
