# Generated by Django 5.2.11 on 2026-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_design_system_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='neutral_color',
            field=models.CharField(blank=True, default='', help_text='Fundo da página no modo claro. Superfícies clareiam para branco. Vazio = creme derivado da primária.', max_length=9, verbose_name='tom neutro (claro)'),
        ),
    ]
