# Generated by Django 5.2.12 on 2026-03-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0002_rename_offering_pro_is_publ_idx_offering_pr_is_publ_6ea7fc_idx_and_more'),
        ('ordering', '0005_session_origin_channel_order_origin_channel'),
        ('shop', '0014_operatoralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('prep', 'Preparo'), ('picking', 'Separação'), ('expedition', 'Expedição')], max_length=20, verbose_name='tipo')),
                ('target_time_minutes', models.PositiveIntegerField(default=10, help_text='Timer fica amarelo após este tempo, vermelho após 2x.', verbose_name='tempo alvo (min)')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='som ativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('config', models.JSONField(blank=True, default=dict, help_text='text_size, dark_mode, refresh_interval, etc.', verbose_name='configurações')),
                ('collections', models.ManyToManyField(blank=True, help_text='Categorias de produto que esta estação processa. Vazio = catch-all.', to='offering.collection', verbose_name='coleções')),
            ],
            options={
                'verbose_name': 'instância KDS',
                'verbose_name_plural': 'instâncias KDS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='[{"sku", "name", "qty", "notes", "checked": false}]', verbose_name='items')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluído')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('kds_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shop.kdsinstance', verbose_name='estação KDS')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='ordering.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'ticket KDS',
                'verbose_name_plural': 'tickets KDS',
                'ordering': ['created_at'],
            },
        ),
    ]
