# Generated by Django 5.2.11 on 2026-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0003_unique_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
    ]
