"""Shopman web views — all storefront, operator, and PWA views."""

from .account import (
    AccountDeleteView,
    AccountView,
    AddressCreateView,
    AddressDeleteView,
    AddressLabelUpdateView,
    AddressSetDefaultView,
    AddressUpdateView,
    DataExportView,
    FoodPreferenceToggleView,
    NotificationPrefsToggleView,
    ProfileDisplayView,
    ProfileEditView,
    ProfileUpdateView,
)
from .auth import (
    AccessLinkLoginView,
    CustomerLookupView,
    DeviceCheckLoginView,
    LoginView,
    RequestCodeView,
    VerifyCodeView,
)
from .bridge import BridgeTokenView
from .cart import (
    AddToCartView,
    ApplyCouponView,
    CartDrawerContentProjView,
    CartPageContentView,
    CartSetQtyBySkuView,
    CartSummaryView,
    CartView,
    QuickAddView,
    RemoveCouponView,
)
from .catalog import (
    MenuView,
    ProductDetailView,
    TipsView,
)
from .checkout import (
    CepLookupView,
    CheckoutOrderSummaryView,
    CheckoutView,
    OrderConfirmationView,
    SimulateIFoodView,
)
from .devices import DeviceListView, DeviceRevokeAllView, DeviceRevokeView
from .home import HomeView
from .info import HowItWorksView, OrderHistoryView, SitemapView
from .kds import (
    KDSDisplayView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketCheckItemView,
    KDSTicketDoneView,
    KDSTicketListPartialView,
)
from .orders import (
    OperatorOrdersView,
    OrderAdvanceView,
    OrderConfirmView,
    OrderDetailPartialView,
    OrderListPartialView,
    OrderMarkPaidView,
    OrderNotesView,
    OrderRejectView,
)
from .payment import MockPaymentConfirmView, PaymentStatusView, PaymentView
from .pos import (
    pos_cancel_last,
    pos_cash_close,
    pos_cash_open,
    pos_cash_sangria,
    pos_close,
    pos_customer_lookup,
    pos_shift_summary,
    pos_view,
)
from .production import bulk_create_work_orders
from .pwa import OfflineView
from .sse_state import SkuStateView
from .tracking import OrderCancelView, OrderStatusPartialView, OrderTrackingView, ReorderView
from .welcome import WelcomeView

__all__ = [
    "BridgeTokenView",
    "TipsView",
    "HomeView",
    "AccountDeleteView",
    "AccountView",
    "AddToCartView",
    "AccessLinkLoginView",
    "ApplyCouponView",
    "AddressCreateView",
    "AddressDeleteView",
    "AddressLabelUpdateView",
    "AddressSetDefaultView",
    "AddressUpdateView",
    "CartPageContentView",
    "CartSetQtyBySkuView",
    "CartSummaryView",
    "CartDrawerContentProjView",
    "CepLookupView",
    "CartView",
    "QuickAddView",
    "CheckoutView",
    "CheckoutOrderSummaryView",
    "SimulateIFoodView",
    "CustomerLookupView",
    "DataExportView",
    "DeviceCheckLoginView",
    "DeviceListView",
    "DeviceRevokeAllView",
    "DeviceRevokeView",
    "FoodPreferenceToggleView",
    "HowItWorksView",
    "NotificationPrefsToggleView",
    "LoginView",
    "MenuView",
    "MockPaymentConfirmView",
    "OperatorOrdersView",
    "OfflineView",
    "OrderAdvanceView",
    "OrderConfirmView",
    "OrderDetailPartialView",
    "OrderMarkPaidView",
    "OrderNotesView",
    "OrderRejectView",
    "OrderCancelView",
    "OrderConfirmationView",
    "OrderHistoryView",
    "OrderStatusPartialView",
    "OrderTrackingView",
    "PaymentStatusView",
    "PaymentView",
    "ProductDetailView",
    "ProfileDisplayView",
    "ProfileEditView",
    "ProfileUpdateView",
    "ReorderView",
    "OrderListPartialView",
    "RemoveCouponView",
    "RequestCodeView",
    "SitemapView",
    "VerifyCodeView",
    "KDSDisplayView",
    "KDSExpeditionActionView",
    "KDSIndexView",
    "KDSTicketCheckItemView",
    "KDSTicketDoneView",
    "KDSTicketListPartialView",
    "pos_cancel_last",
    "pos_cash_close",
    "pos_cash_open",
    "pos_cash_sangria",
    "pos_close",
    "pos_customer_lookup",
    "pos_shift_summary",
    "pos_view",
    "bulk_create_work_orders",
    "WelcomeView",
    "SkuStateView",
]
