# Generated by Django 5.2.11 on 2026-03-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order', 'Pedido'), ('contact', 'Contato'), ('note', 'Nota'), ('visit', 'Visita'), ('loyalty', 'Fidelidade'), ('system', 'Sistema')], db_index=True, max_length=20, verbose_name='tipo')),
                ('title', models.CharField(help_text='Resumo curto do evento', max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, help_text='Detalhes adicionais do evento', verbose_name='descrição')),
                ('channel', models.CharField(blank=True, help_text='Canal de origem (whatsapp, pdv, ecommerce, etc.)', max_length=50, verbose_name='canal')),
                ('reference', models.CharField(blank=True, help_text='ID externo (ex: order:123, ticket:456)', max_length=100, verbose_name='referência')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados extras do evento (JSON livre)', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('created_by', models.CharField(blank=True, help_text='Usuário ou sistema que criou o evento', max_length=100, verbose_name='criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='attending.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'evento da timeline',
                'verbose_name_plural': 'eventos da timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='attending_t_custome_7978a3_idx'), models.Index(fields=['customer', 'event_type'], name='attending_t_custome_f6d0d4_idx')],
            },
        ),
    ]
