# Generated by Django 6.0.5 on 2026-05-29 19:33

import django.db.models.deletion
import shopman.doorman.models.pin_credential
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(help_text='HMAC-SHA256 do PIN. Nunca armazena plaintext.', max_length=64, verbose_name='hash do PIN')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas falhas')),
                ('max_attempts', models.PositiveSmallIntegerField(default=shopman.doorman.models.pin_credential._default_max_attempts, verbose_name='máximo de tentativas')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='última verificação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_credential', to=settings.AUTH_USER_MODEL, verbose_name='principal')),
            ],
            options={
                'verbose_name': 'credencial PIN',
                'verbose_name_plural': 'credenciais PIN',
                'db_table': 'doorman_pin_credential',
                'ordering': ['-updated_at'],
            },
        ),
    ]
