# Generated by Django 6.0.5 on 2026-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0002_pincredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincredential',
            name='badge_hash',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='HMAC-SHA256 do token do crachá (código de barras). Alternativa ao PIN. Nunca armazena plaintext.', max_length=64, null=True, unique=True, verbose_name='hash do crachá'),
        ),
    ]
