# Generated by Django 6.0.5 on 2026-07-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0003_pincredential_badge_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincredential',
            name='must_change',
            field=models.BooleanField(default=False, verbose_name='trocar no próximo uso'),
        ),
    ]
