# Generated by Django 5.2.11 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionitem',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SKU'),
        ),
    ]
