# Generated by Django 6.0.5 on 2026-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0003_order_channel_external_ref_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='chave da sessão')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='sequência')),
                ('type', models.CharField(db_index=True, max_length=64, verbose_name='tipo')),
                ('actor', models.CharField(max_length=128, verbose_name='ator')),
                ('payload', models.JSONField(default=dict, help_text='Delta da ação. Ex: {"sku": "PAO", "qty_before": 3, "qty_after": 0}', verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'evento da sessão',
                'verbose_name_plural': 'eventos da sessão',
                'ordering': ('session_key', 'seq'),
                'constraints': [models.UniqueConstraint(fields=('session_key', 'seq'), name='ord_uniq_session_event_seq')],
            },
        ),
    ]
