# Generated by Django 6.0.7 on 2026-07-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0004_sessionevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='directive',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('dedupe_key', ''), _negated=True), ('status__in', ('queued', 'running'))), fields=('topic', 'dedupe_key'), name='orderman_directive_live_dedupe_unique'),
        ),
    ]
