# Generated by Django 6.0.5 on 2026-07-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0005_directive_orderman_directive_live_dedupe_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillment',
            options={'ordering': ('-created_at',), 'verbose_name': 'expedição', 'verbose_name_plural': 'expedições'},
        ),
        migrations.AlterModelOptions(
            name='fulfillmentitem',
            options={'verbose_name': 'item da expedição', 'verbose_name_plural': 'itens da expedição'},
        ),
        migrations.AlterField(
            model_name='fulfillmentitem',
            name='fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orderman.fulfillment', verbose_name='expedição'),
        ),
    ]
