# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0006_alter_fulfillment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directive',
            options={'verbose_name': 'ação pendente', 'verbose_name_plural': 'ações pendentes'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'comanda', 'verbose_name_plural': 'comandas'},
        ),
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ('session_key', 'seq'), 'verbose_name': 'evento da comanda', 'verbose_name_plural': 'eventos da comanda'},
        ),
        migrations.AlterModelOptions(
            name='sessionitem',
            options={'verbose_name': 'item da comanda', 'verbose_name_plural': 'itens da comanda'},
        ),
    ]
