# Generated by Django 6.0.5 on 2026-07-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref',
            options={'verbose_name': 'Referência', 'verbose_name_plural': 'Referências'},
        ),
        migrations.AlterModelOptions(
            name='refsequence',
            options={'verbose_name': 'Sequência de referência', 'verbose_name_plural': 'Sequências de referência'},
        ),
        migrations.AlterField(
            model_name='refsequence',
            name='last_value',
            field=models.PositiveIntegerField(default=0, verbose_name='último valor'),
        ),
    ]
