# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0002_alter_ref_options_alter_refsequence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref',
            options={'verbose_name': 'referência', 'verbose_name_plural': 'referências'},
        ),
        migrations.AlterModelOptions(
            name='refsequence',
            options={'verbose_name': 'sequência de referência', 'verbose_name_plural': 'sequências de referência'},
        ),
    ]
