// KDS contract types. The structural shapes come from the generated mirror
// (app/generated/kdsContract.ts — source of truth:
// shopman/backstage/projections/kds.py, regenerated by
// `python manage.py export_kds_schema` and drift-guarded in the Django CI).
// This module only narrows fields the backend types as plain `str` and adds
// the API envelopes (shopman/backstage/api/kds.py response shapes).

import type {
  KDSBoardProjection as KDSBoardContract,
  KDSCustomerStatusProjection,
  KDSExpeditionCardProjection,
  KDSInstanceSummaryProjection,
  KDSTicketProjection as KDSTicketContract,
} from "~/generated/kdsContract";

export type {
  KDSCustomerOrderProjection,
  KDSCustomerStatusProjection,
  KDSExpeditionCardProjection,
  KDSInstanceSummaryProjection,
  KDSItemProjection,
} from "~/generated/kdsContract";

export type KDSTimerClass = "timer-ok" | "timer-warning" | "timer-late";

export interface KDSTicketProjection extends KDSTicketContract {
  timer_class: KDSTimerClass;
}

export interface KDSBoardProjection extends KDSBoardContract {
  /** Prep stations hold KDSTicketProjection; expedition holds KDSExpeditionCardProjection. */
  tickets: (KDSTicketProjection | KDSExpeditionCardProjection)[];
  cancelled_tickets: KDSTicketProjection[];
  recent_done: KDSTicketProjection[]; // para recall (desfazer finalização)
}

// API envelopes (shopman/backstage/api/kds.py response shapes).
export interface KDSIndexResponse { instances: KDSInstanceSummaryProjection[] }
export interface KDSBoardResponse { board: KDSBoardProjection }
export interface KDSTicketResponse { ticket: KDSTicketProjection }
export interface KDSCustomerStatusResponse { status: KDSCustomerStatusProjection }
