from .bridge import BridgeTokenView
from .home import HomeView
from .account import (
    AccountDeleteView,
    AccountView,
    AddressCreateView,
    AddressDeleteView,
    AddressSetDefaultView,
    AddressUpdateView,
    DataExportView,
    FoodPreferenceToggleView,
    NotificationPrefsToggleView,
    ProfileDisplayView,
    ProfileEditView,
    ProfileUpdateView,
)
from .auth import (
    AccessLinkLoginView,
    CustomerLookupView,
    DeviceCheckLoginView,
    LoginView,
    RequestCodeView,
    VerifyCodeView,
)
from .cart import (
    AddToCartView,
    ApplyCouponView,
    CartCheckView,
    CartContentPartialView,
    CartDrawerContentView,
    CartSummaryView,
    CartView,
    FloatingCartBarView,
    QuickAddView,
    RemoveCartItemView,
    RemoveCouponView,
    UpdateCartItemView,
)
from .catalog import MenuSearchView, MenuView, ProductDetailView
from .checkout import CepLookupView, CheckoutView, OrderConfirmationView
from .devices import DeviceListView, DeviceRevokeAllView, DeviceRevokeView
from .info import HowItWorksView, OrderHistoryView, SitemapView
from .payment import MockPaymentConfirmView, PaymentStatusView, PaymentView
from .pwa import OfflineView
from .pedidos import (
    GestorPedidosView,
    OrderListPartialView,
    PedidoAdvanceView,
    PedidoConfirmView,
    PedidoDetailPartialView,
    PedidoNotesView,
    PedidoRejectView,
)
from .tracking import OrderCancelView, OrderStatusPartialView, OrderTrackingView, ReorderView
from shop.views.pos import pos_close, pos_customer_lookup, pos_view
from .kds import (
    KDSDisplayView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketCheckItemView,
    KDSTicketDoneView,
    KDSTicketListPartialView,
)

__all__ = [
    "BridgeTokenView",
    "HomeView",
    "AccountDeleteView",
    "AccountView",
    "AddToCartView",
    "AccessLinkLoginView",
    "ApplyCouponView",
    "AddressCreateView",
    "AddressDeleteView",
    "AddressSetDefaultView",
    "AddressUpdateView",
    "CartCheckView",
    "CartContentPartialView",
    "CartSummaryView",
    "CartDrawerContentView",
    "CepLookupView",
    "CartView",
    "QuickAddView",
    "CheckoutView",
    "CustomerLookupView",
    "DataExportView",
    "DeviceCheckLoginView",
    "DeviceListView",
    "DeviceRevokeAllView",
    "DeviceRevokeView",
    "FloatingCartBarView",
    "FoodPreferenceToggleView",
    "HowItWorksView",
    "MenuSearchView",
    "NotificationPrefsToggleView",
    "LoginView",
    "MenuView",
    "MockPaymentConfirmView",
    "OfflineView",
    "OrderCancelView",
    "OrderConfirmationView",
    "OrderHistoryView",
    "OrderStatusPartialView",
    "OrderTrackingView",
    "PaymentStatusView",
    "PaymentView",
    "ProductDetailView",
    "ProfileDisplayView",
    "ProfileEditView",
    "ProfileUpdateView",
    "ReorderView",
    "GestorPedidosView",
    "OrderListPartialView",
    "PedidoAdvanceView",
    "PedidoConfirmView",
    "PedidoDetailPartialView",
    "PedidoNotesView",
    "PedidoRejectView",
    "RemoveCartItemView",
    "RemoveCouponView",
    "RequestCodeView",
    "SitemapView",
    "UpdateCartItemView",
    "VerifyCodeView",
    "KDSDisplayView",
    "KDSExpeditionActionView",
    "KDSIndexView",
    "KDSTicketCheckItemView",
    "KDSTicketDoneView",
    "KDSTicketListPartialView",
    "pos_close",
    "pos_customer_lookup",
    "pos_view",
]
