# Generated by Django 5.2.11 on 2026-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('captured', 'Capturado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
