# Generated by Django 5.2.11 on 2026-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_id', ''), _negated=True), fields=('gateway', 'gateway_id'), name='pay_intent_gateway_id_unique'),
        ),
    ]
