# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0002_alter_paymentintent_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados de resposta do gateway. Populado automaticamente. Ex: {"pix_qr_code": "00020126...", "txid": "abc123"}'),
        ),
    ]
