# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0004_intent_idempotency_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'ordering': ['-created_at'], 'verbose_name': 'cobrança', 'verbose_name_plural': 'cobranças'},
        ),
    ]
