# Generated by Django 5.2.11 on 2026-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='ingredients_text',
            field=models.TextField(blank=True, help_text='Lista de ingredientes em ordem decrescente de peso (ANVISA). Ex: Farinha de trigo, água, fermento natural, sal marinho.', verbose_name='ingredientes'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='nutrition_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Tabela nutricional por porção (gerenciada via form dedicado).', verbose_name='informações nutricionais'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_text',
            field=models.TextField(blank=True, help_text='Lista de ingredientes em ordem decrescente de peso (ANVISA). Ex: Farinha de trigo, água, fermento natural, sal marinho.', verbose_name='ingredientes'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Tabela nutricional por porção (gerenciada via form dedicado).', verbose_name='informações nutricionais'),
        ),
    ]
