# Generated by Django 5.2.11 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='offering_pr_is_publ_6ea7fc_idx',
            old_name='offering_pro_is_publ_idx',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_batch_produced',
            field=models.BooleanField(default=False, help_text='Produzido em lotes (para Crafting)', verbose_name='produção em lote'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, help_text='Validade em dias. Vazio=não perecível, 0=mesmo dia', null=True, verbose_name='validade (dias)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ref',
            field=models.SlugField(unique=True, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_batch_produced',
            field=models.BooleanField(default=False, help_text='Produzido em lotes (para Crafting)', verbose_name='produção em lote'),
        ),
    ]
