# Generated by Django 5.2.11 on 2026-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0002_add_ingredients_and_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='projected_skus',
            field=models.JSONField(default=list, verbose_name='SKUs projetados'),
        ),
    ]
