# Generated by Django 5.2.12 on 2026-04-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0002_rename_offering_pro_is_publ_idx_offering_pr_is_publ_6ea7fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='storage_tip',
            field=models.CharField(blank=True, help_text='Breve dica de conservação exibida na página do produto', max_length=300, verbose_name='dica de conservação'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unit_weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Peso aproximado por unidade em gramas. Ex: 150 para pão francês', null=True, verbose_name='peso por unidade (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_tip',
            field=models.CharField(blank=True, help_text='Breve dica de conservação exibida na página do produto', max_length=300, verbose_name='dica de conservação'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Peso aproximado por unidade em gramas. Ex: 150 para pão francês', null=True, verbose_name='peso por unidade (g)'),
        ),
    ]
