# Generated by Django 5.2.11 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0003_listing_projected_skus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU'),
        ),
    ]
