# Generated by Django 6.0.5 on 2026-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0005_listing_projection_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='rule',
            field=models.JSONField(blank=True, default=dict, verbose_name='regra'),
        ),
    ]
