# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0006_collection_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'coleção', 'verbose_name_plural': 'coleções'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'item de coleção', 'verbose_name_plural': 'itens de coleção'},
        ),
        migrations.AlterModelOptions(
            name='historicallistingitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical item de vitrine', 'verbose_name_plural': 'historical itens de vitrine'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'vitrine', 'verbose_name_plural': 'vitrines'},
        ),
        migrations.AlterModelOptions(
            name='listingitem',
            options={'ordering': ['listing', 'product__name'], 'verbose_name': 'item de vitrine', 'verbose_name_plural': 'itens de vitrine'},
        ),
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'verbose_name': 'componente de produto', 'verbose_name_plural': 'componentes de produto'},
        ),
    ]
