# Generated by Django 5.2.11 on 2026-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='listing_ref',
            field=models.CharField(blank=True, default='', help_text='Ref da Listing que serve como catálogo deste canal', max_length=50, verbose_name='listagem'),
        ),
    ]
