# Generated by Django 5.2.11 on 2026-03-25 08:26

import shopman.omniman.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0003_fulfillment_dispatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='ChannelConfig schema (7 aspectos). Chaves: confirmation {mode, timeout_minutes}, payment {method, timeout_minutes}, stock {hold_ttl_minutes, safety_margin, planned_hold_ttl_hours}, pipeline {on_commit, on_confirmed, on_cancelled, ...} (listas de topics), notifications {backend, fallback, routing}, rules {validators, modifiers, checks}, flow {transitions, terminal_statuses, auto_transitions, auto_sync_fulfillment}. Use presets: pos(), remote(), marketplace().', verbose_name='configuração'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='payload',
            field=models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Dados da tarefa. Schema depende do topic. Ex: stock.hold → {"sku": "PAO-FRANCES", "qty": 10}', verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados de entrega. Ex: {"tracking_code": "BR123", "carrier": "correios"}', verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Dados extras do pedido. Formato livre. Ex: {"notes": "Sem cebola", "delivery_address": "Rua X, 123"}', verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=shopman.omniman.models.session.DecimalEncoder, help_text='Snapshot selado do pedido no momento da criação. Não editar manualmente.', verbose_name='snapshot'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='payload',
            field=models.JSONField(default=dict, help_text='Dados do evento. Ex: {"new_status": "confirmed"} ou {"error": "motivo"}', verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do item. Ex: {"customization": "sem gluten", "gift_wrap": true}', verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.JSONField(default=dict, help_text='Dados da sessão (checks, validações). Populado automaticamente pelo sistema.', verbose_name='dados'),
        ),
        migrations.AlterField(
            model_name='session',
            name='pricing',
            field=models.JSONField(blank=True, default=dict, help_text='Resultado da precificação. Populado automaticamente pelos modifiers.', verbose_name='precificação'),
        ),
        migrations.AlterField(
            model_name='session',
            name='pricing_trace',
            field=models.JSONField(blank=True, default=list, help_text='Trace de auditoria dos modifiers. Populado automaticamente.', verbose_name='trace de precificação'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados do item. Ex: {"customization": "extra queijo"}', verbose_name='metadados'),
        ),
    ]
