# Generated by Django 5.2.12 on 2026-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0006_order_status_processing_to_preparing'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='flow',
            field=models.CharField(default='base', help_text='Nome da classe de Flow no registry (shopman.flows): base, local, pos, totem, remote, web, whatsapp, manychat, marketplace, ifood.', max_length=32, verbose_name='flow'),
        ),
    ]
