# Generated by Django 5.2.12 on 2026-04-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0009_directive_error_code_dedupe_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='edit_policy',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='pricing_policy',
        ),
    ]
