# Generated by Django 5.2.11 on 2026-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Nelson Boulangerie', max_length=100, verbose_name='Nome da marca')),
                ('short_name', models.CharField(default='Nelson', max_length=30, verbose_name='Nome curto')),
                ('tagline', models.CharField(blank=True, default='Padaria Artesanal', max_length=200, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, default='Padaria artesanal premium.\nFermentação natural, tradição francesa e japonesa.', verbose_name='Descrição')),
                ('theme_color', models.CharField(default='#C5A55A', max_length=7, verbose_name='Cor principal')),
                ('background_color', models.CharField(default='#F5F0EB', max_length=7, verbose_name='Cor de fundo')),
                ('default_ddd', models.CharField(default='43', max_length=3, verbose_name='DDD padrão')),
                ('default_city', models.CharField(default='Londrina', max_length=100, verbose_name='Cidade padrão')),
                ('location', models.CharField(blank=True, default='Londrina — PR', max_length=200, verbose_name='Localização')),
                ('whatsapp_number', models.CharField(blank=True, default='5543999999999', max_length=20, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuração do Storefront',
                'verbose_name_plural': 'Configuração do Storefront',
            },
        ),
    ]
