"""Backstage views — operator-facing surfaces (KDS, POS, Gestor, Fechamento, Produção)."""

from .alerts import alert_ack, alerts_badge, alerts_panel
from .closing import closing_view
from .kds import (
    KDSDisplayView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketCheckItemView,
    KDSTicketDoneView,
    KDSTicketListPartialView,
)
from .orders import (
    AlertAcknowledgeView,
    OperatorOrdersView,
    OrderAdvanceView,
    OrderConfirmView,
    OrderDetailPartialView,
    OrderHistoricoView,
    OrderListPartialView,
    OrderMarkPaidView,
    OrderNotesView,
    OrderRejectView,
)
from .pos import (
    pos_cancel_last,
    pos_cash_close,
    pos_cash_open,
    pos_cash_sangria,
    pos_close,
    pos_customer_lookup,
    pos_load_session,
    pos_park,
    pos_sessions,
    pos_shift_summary,
    pos_view,
)
from .production import (
    bulk_create_work_orders,
    production_advance_step_view,
    production_dashboard_view,
    production_kds_cards_view,
    production_kds_view,
    production_reports_view,
    production_work_order_orders_view,
    production_view,
    production_void_view,
)

__all__ = [
    "closing_view",
    "alert_ack",
    "alerts_badge",
    "alerts_panel",
    "KDSDisplayView",
    "KDSExpeditionActionView",
    "KDSIndexView",
    "KDSTicketCheckItemView",
    "KDSTicketDoneView",
    "KDSTicketListPartialView",
    "OperatorOrdersView",
    "OrderAdvanceView",
    "OrderConfirmView",
    "OrderDetailPartialView",
    "OrderHistoricoView",
    "OrderListPartialView",
    "OrderMarkPaidView",
    "OrderNotesView",
    "OrderRejectView",
    "AlertAcknowledgeView",
    "bulk_create_work_orders",
    "production_advance_step_view",
    "production_dashboard_view",
    "production_kds_cards_view",
    "production_kds_view",
    "production_reports_view",
    "production_work_order_orders_view",
    "production_view",
    "production_void_view",
    "pos_cancel_last",
    "pos_cash_close",
    "pos_cash_open",
    "pos_cash_sangria",
    "pos_close",
    "pos_customer_lookup",
    "pos_load_session",
    "pos_park",
    "pos_sessions",
    "pos_shift_summary",
    "pos_view",
]
