# Generated by Django 5.2.11 on 2026-03-24 10:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('explicit', 'Explícita'), ('inferred', 'Inferida'), ('restriction', 'Restrição')], default='explicit', max_length=20, verbose_name='tipo')),
                ('category', models.CharField(help_text="Categoria da preferência (ex: 'dietética', 'sabor', 'embalagem')", max_length=50, verbose_name='categoria')),
                ('key', models.CharField(help_text="Nome da preferência (ex: 'sem_lactose', 'pao_favorito')", max_length=100, verbose_name='chave')),
                ('value', models.JSONField(default=dict, help_text='Valor da preferência (pode ser bool, string, lista, etc.)', verbose_name='valor')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0.00 a 1.00 - confiança na preferência inferida', max_digits=3, verbose_name='confiança')),
                ('source', models.CharField(blank=True, help_text="Origem da preferência (ex: 'pedido:123', 'formulário', 'chat')", max_length=100, verbose_name='origem')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'preferência',
                'verbose_name_plural': 'preferências',
                'ordering': ['category', 'key'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'category', 'key'), name='customers_unique_preference')],
            },
        ),
    ]
