# Generated by Django 6.0.5 on 2026-06-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Identificador do insumo (ex.: INS-FARINHA-T65).', max_length=64, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('unit', models.CharField(choices=[('un', 'unidade'), ('kg', 'quilograma'), ('g', 'grama'), ('l', 'litro'), ('ml', 'mililitro')], default='un', max_length=8, verbose_name='Unidade')),
                ('shelf_life_days', models.IntegerField(blank=True, help_text='Validade padrão do insumo em dias. Vazio = não perecível.', null=True, verbose_name='Validade padrão (dias)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Perfil opcional (nutrição, alérgenos, etc.).', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(db_index=True, help_text='Identificador do fornecedor (ex.: SUP-MOINHO-SP).', max_length=64, unique=True, verbose_name='Referência')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('document', models.CharField(blank=True, default='', max_length=32, verbose_name='CNPJ/Documento')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefone')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierMaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_q', models.BigIntegerField(help_text='Custo por unidade do insumo, em centavos.', verbose_name='Custo (centavos)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Marca o custo canônico deste insumo (alimenta o custeio).', verbose_name='Preferencial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_costs', to='buyman.material', verbose_name='Insumo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='buyman.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Custo de insumo por fornecedor',
                'verbose_name_plural': 'Custos de insumo por fornecedor',
                'ordering': ['material', 'supplier'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'material'), name='buyman_supplier_material_unique'), models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('material',), name='buyman_one_preferred_cost_per_material')],
            },
        ),
    ]
