# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['sku'], 'verbose_name': 'insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='suppliermaterialcost',
            options={'ordering': ['material', 'supplier'], 'verbose_name': 'custo de insumo por fornecedor', 'verbose_name_plural': 'custos de insumo por fornecedor'},
        ),
    ]
