# Generated by Django 5.2.11 on 2026-04-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0010_remove_cashmovement_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], max_length=10, verbose_name='tipo')),
                ('value', models.IntegerField(help_text='Percentual (0-100) ou valor fixo em centavos', verbose_name='valor')),
                ('valid_from', models.DateTimeField(verbose_name='válido de')),
                ('valid_until', models.DateTimeField(verbose_name='válido até')),
                ('skus', models.JSONField(blank=True, default=list, help_text='SKUs afetados (vazio = todos). Ex: ["PAO-FRANCES", "CROISSANT"]', verbose_name='SKUs')),
                ('collections', models.JSONField(blank=True, default=list, help_text='Collection refs afetados (vazio = todos). Ex: ["paes-artesanais", "confeitaria"]', verbose_name='coleções')),
                ('min_order_q', models.IntegerField(default=0, help_text='Valor mínimo do pedido em centavos (0 = sem mínimo)', verbose_name='pedido mínimo (centavos)')),
                ('fulfillment_types', models.JSONField(blank=True, default=list, help_text='Tipos de entrega (vazio = todos). Ex: ["delivery", "pickup"]', verbose_name='tipos de entrega')),
                ('customer_segments', models.JSONField(blank=True, default=list, help_text='Segmentos RFM para targeting (vazio = todos). Ex: ["champions", "loyal"]', verbose_name='segmentos de cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('zone_type', models.CharField(choices=[('cep_prefix', 'Prefixo de CEP'), ('neighborhood', 'Bairro')], default='cep_prefix', max_length=20, verbose_name='tipo de zona')),
                ('match_value', models.CharField(help_text="Para 'Prefixo de CEP': dígitos iniciais sem hífen (ex: '860' cobre 860xx-xxx). Para 'Bairro': nome exato do bairro (comparação sem maiúsculas/minúsculas). ", max_length=100, verbose_name='valor de correspondência')),
                ('fee_q', models.PositiveIntegerField(default=0, help_text='Taxa em centavos. 0 = entrega grátis.', verbose_name='taxa de entrega (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Menor número = maior prioridade dentro do mesmo tipo.', verbose_name='ordem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='shop.shop', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'zona de entrega',
                'verbose_name_plural': 'zonas de entrega',
                'ordering': ['zone_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='código')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='usos máximos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='storefront.promotion', verbose_name='promoção')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
    ]
