# Generated by Django 5.2.11 on 2026-06-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_promotion_birthday_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('channel_ref', models.CharField(default='web', max_length=32)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=64)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sku', 'notified_at'], name='storefront__sku_a4e9b8_idx')],
            },
        ),
    ]
