# Generated by Django 5.2.11 on 2026-06-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_stockalertsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ref', models.CharField(db_index=True, max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer_ref', 'sku'), name='uniq_customer_favorite')],
            },
        ),
    ]
