# Generated by Django 6.0.5 on 2026-06-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cleanup_orphan_content_types'),
        ('storefront', '0004_customerfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='mode',
            field=models.CharField(choices=[('override', 'Sobrepor taxa (fixa)'), ('exclude', 'Não entregar (bloquear)')], default='override', help_text="'Sobrepor taxa': usa a taxa fixa abaixo no lugar da faixa de distância. 'Não entregar': bloqueia o checkout para este CEP/bairro.", max_length=20, verbose_name='modo'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='fee_q',
            field=models.PositiveIntegerField(default=0, help_text="Taxa em centavos no modo 'Sobrepor taxa'. 0 = entrega grátis.", verbose_name='taxa de entrega (centavos)'),
        ),
        migrations.CreateModel(
            name='DeliveryDistanceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_km', models.DecimalField(decimal_places=2, help_text='Limite superior inclusivo da faixa, em km (ex.: 3.00 cobre até 3 km).', max_digits=6, verbose_name='distância máxima (km)')),
                ('fee_q', models.PositiveIntegerField(default=0, help_text='Taxa em centavos. 0 = entrega grátis.', verbose_name='taxa de entrega (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Desempate entre faixas com o mesmo limite. Menor = maior prioridade.', verbose_name='ordem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_distance_bands', to='shop.shop', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'faixa de distância de entrega',
                'verbose_name_plural': 'faixas de distância de entrega',
                'ordering': ['max_distance_km', 'sort_order'],
            },
        ),
    ]
