# Generated by Django 6.0.5 on 2026-07-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_deliveryzone_mode_alter_deliveryzone_fee_q_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'favorito', 'verbose_name_plural': 'favoritos'},
        ),
        migrations.AlterModelOptions(
            name='stockalertsubscription',
            options={'verbose_name': 'aviso de reposição', 'verbose_name_plural': 'avisos de reposição'},
        ),
    ]
