# Generated by Django 6.0.5 on 2026-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_customerfavorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertsubscription',
            name='alert_type',
            field=models.CharField(choices=[('stock_back', 'voltou ao estoque'), ('production_ready', 'saiu do forno')], default='stock_back', max_length=24),
        ),
        migrations.AddIndex(
            model_name='stockalertsubscription',
            index=models.Index(fields=['sku', 'alert_type', 'notified_at'], name='storefront__sku_e32054_idx'),
        ),
    ]
