"""Backstage API URL configuration."""

from __future__ import annotations

from django.urls import path

from .alerts import AlertAckView, AlertListView
from .catalog import (
    CatalogBulkView,
    CatalogCellView,
    CatalogMatrixView,
    CatalogProductView,
)
from .kds import (
    KDSBoardView,
    KDSCustomerStatusView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketAcknowledgeView,
    KDSTicketDoneView,
    KDSTicketItemView,
    KDSTicketRecallView,
)
from .operations import (
    DayClosingView,
    OperatorEligibleView,
    OperatorLockView,
    OperatorSessionView,
    OperatorUnlockView,
    OrderAdvanceView,
    OrderAssignView,
    OrderCancellationReasonsView,
    OrderCancelView,
    OrderCommentView,
    OrderConfirmView,
    OrderDetailView,
    OrderNotesView,
    OrderQueueView,
    OrderRejectView,
    OrderRequeueFiscalView,
    OrderSettleDeliveryCashView,
    OrderUnassignView,
    POSCancelRecentSaleView,
    POSCashCloseView,
    POSCashMovementView,
    POSCashOpenView,
    POSCloseSaleView,
    POSCustomerLookupView,
    POSCustomerResolveView,
    POSCustomerSearchView,
    POSReviewSaleView,
    POSTabClearView,
    POSTabCreateView,
    POSTabFireView,
    POSTabMoveLinesView,
    POSTabOpenView,
    POSTabRenameView,
    POSTabSaveView,
    POSTabUnfireView,
    POSView,
    ProductionBoardView,
    ProductionKDSView,
    WorkOrderAdvanceStepView,
    WorkOrderFinishView,
    WorkOrderPlanView,
    WorkOrderQuickFinishView,
    WorkOrderStartView,
    WorkOrderVoidView,
)

urlpatterns = [
    # KDS
    path("kds/", KDSIndexView.as_view(), name="api-backstage-kds-index"),
    path("kds/cliente/", KDSCustomerStatusView.as_view(), name="api-backstage-kds-customer"),
    path("kds/<slug:ref>/", KDSBoardView.as_view(), name="api-backstage-kds-board"),
    path("kds/tickets/<int:ticket_pk>/items/", KDSTicketItemView.as_view(), name="api-backstage-kds-ticket-item"),
    path("kds/tickets/<int:ticket_pk>/done/", KDSTicketDoneView.as_view(), name="api-backstage-kds-ticket-done"),
    path("kds/tickets/<int:ticket_pk>/recall/", KDSTicketRecallView.as_view(), name="api-backstage-kds-ticket-recall"),
    path("kds/tickets/<int:ticket_pk>/acknowledge/", KDSTicketAcknowledgeView.as_view(), name="api-backstage-kds-ticket-acknowledge"),
    path("kds/expedition/<int:order_pk>/action/", KDSExpeditionActionView.as_view(), name="api-backstage-kds-expedition"),
    # Operations — read views
    path("pos/", POSView.as_view(), name="api-backstage-pos"),
    # Operador (PIN/crachá) — genérico, compartilhado por todas as surfaces (inclui POS)
    path("operator/session/", OperatorSessionView.as_view(), name="api-backstage-operator-session"),
    path("operator/eligible/", OperatorEligibleView.as_view(), name="api-backstage-operator-eligible"),
    path("operator/unlock/", OperatorUnlockView.as_view(), name="api-backstage-operator-unlock"),
    path("operator/lock/", OperatorLockView.as_view(), name="api-backstage-operator-lock"),
    path("production/", ProductionBoardView.as_view(), name="api-backstage-production"),
    path("production/kds/", ProductionKDSView.as_view(), name="api-backstage-production-kds"),
    path("closing/", DayClosingView.as_view(), name="api-backstage-closing"),
    path("orders/", OrderQueueView.as_view(), name="api-backstage-orders"),
    # Catalog matrix (produto × superfície)
    path("catalog/", CatalogMatrixView.as_view(), name="api-backstage-catalog"),
    path("catalog/cell/", CatalogCellView.as_view(), name="api-backstage-catalog-cell"),
    path("catalog/product/", CatalogProductView.as_view(), name="api-backstage-catalog-product"),
    path("catalog/bulk/", CatalogBulkView.as_view(), name="api-backstage-catalog-bulk"),
    # Orders — operator actions
    path("orders/<str:ref>/", OrderDetailView.as_view(), name="api-backstage-order-detail"),
    path("orders/<str:ref>/advance/", OrderAdvanceView.as_view(), name="api-backstage-order-advance"),
    path("orders/<str:ref>/confirm/", OrderConfirmView.as_view(), name="api-backstage-order-confirm"),
    path("orders/<str:ref>/reject/", OrderRejectView.as_view(), name="api-backstage-order-reject"),
    path("orders/<str:ref>/cancel/", OrderCancelView.as_view(), name="api-backstage-order-cancel"),
    path("orders/<str:ref>/cancellation-reasons/", OrderCancellationReasonsView.as_view(), name="api-backstage-order-cancellation-reasons"),
    path("orders/<str:ref>/settle-delivery-cash/", OrderSettleDeliveryCashView.as_view(), name="api-backstage-order-settle-delivery-cash"),
    path("orders/<str:ref>/requeue-fiscal/", OrderRequeueFiscalView.as_view(), name="api-backstage-order-requeue-fiscal"),
    path("orders/<str:ref>/notes/", OrderNotesView.as_view(), name="api-backstage-order-notes"),
    path("orders/<str:ref>/assign/", OrderAssignView.as_view(), name="api-backstage-order-assign"),
    path("orders/<str:ref>/unassign/", OrderUnassignView.as_view(), name="api-backstage-order-unassign"),
    path("orders/<str:ref>/comment/", OrderCommentView.as_view(), name="api-backstage-order-comment"),
    # Operator alerts
    path("alerts/", AlertListView.as_view(), name="api-backstage-alerts"),
    path("alerts/<int:pk>/ack/", AlertAckView.as_view(), name="api-backstage-alert-ack"),
    # Production — work order actions
    path("production/plan/", WorkOrderPlanView.as_view(), name="api-backstage-wo-plan"),
    path("production/<int:wo_id>/start/", WorkOrderStartView.as_view(), name="api-backstage-wo-start"),
    path("production/<int:wo_id>/finish/", WorkOrderFinishView.as_view(), name="api-backstage-wo-finish"),
    path("production/<int:wo_id>/advance-step/", WorkOrderAdvanceStepView.as_view(), name="api-backstage-wo-advance"),
    path("production/quick-finish/", WorkOrderQuickFinishView.as_view(), name="api-backstage-wo-quick-finish"),
    path("production/<int:wo_id>/void/", WorkOrderVoidView.as_view(), name="api-backstage-wo-void"),
    # POS — cash session actions
    path("pos/cash/open/", POSCashOpenView.as_view(), name="api-backstage-pos-cash-open"),
    path("pos/cash/close/", POSCashCloseView.as_view(), name="api-backstage-pos-cash-close"),
    path("pos/cash/movement/", POSCashMovementView.as_view(), name="api-backstage-pos-cash-movement"),
    # POS — tab (comanda) lifecycle
    path("pos/tabs/", POSTabCreateView.as_view(), name="api-backstage-pos-tab-create"),
    path("pos/tabs/<str:tab_ref>/open/", POSTabOpenView.as_view(), name="api-backstage-pos-tab-open"),
    path("pos/tabs/save/", POSTabSaveView.as_view(), name="api-backstage-pos-tab-save"),
    path("pos/tabs/rename/", POSTabRenameView.as_view(), name="api-backstage-pos-tab-rename"),
    path("pos/tabs/move-lines/", POSTabMoveLinesView.as_view(), name="api-backstage-pos-tab-move-lines"),
    path("pos/tabs/fire/", POSTabFireView.as_view(), name="api-backstage-pos-tab-fire"),
    path("pos/tabs/unfire/", POSTabUnfireView.as_view(), name="api-backstage-pos-tab-unfire"),
    path("pos/tabs/<str:session_key>/clear/", POSTabClearView.as_view(), name="api-backstage-pos-tab-clear"),
    path("pos/sale/review/", POSReviewSaleView.as_view(), name="api-backstage-pos-review-sale"),
    path("pos/sale/close/", POSCloseSaleView.as_view(), name="api-backstage-pos-close-sale"),
    path("pos/sale/recent/cancel/", POSCancelRecentSaleView.as_view(), name="api-backstage-pos-cancel-recent-sale"),
    path("pos/customer/lookup/", POSCustomerLookupView.as_view(), name="api-backstage-pos-customer-lookup"),
    path("pos/customer/search/", POSCustomerSearchView.as_view(), name="api-backstage-pos-customer-search"),
    path("pos/customer/resolve/", POSCustomerResolveView.as_view(), name="api-backstage-pos-customer-resolve"),
]
