"""Backstage API URL configuration."""

from __future__ import annotations

from django.urls import path

from .alerts import AlertAckView, AlertListView
from .catalog import (
    CatalogBulkPriceView,
    CatalogBulkView,
    CatalogCellView,
    CatalogMatrixView,
    CatalogProductDetailView,
    CatalogProductView,
    CatalogReorderCollectionsView,
    CatalogReorderItemsView,
    CatalogResyncView,
    CatalogSocialView,
    CatalogSyncStatusView,
)
from .hub import HubView
from .kds import (
    KDSBoardView,
    KDSCustomerStatusView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketAcknowledgeView,
    KDSTicketDoneView,
    KDSTicketItemView,
    KDSTicketRecallView,
)
from .operations import (
    DayClosingView,
    OperatorEligibleView,
    OperatorLockView,
    OperatorLoginView,
    OperatorPinChangeView,
    OperatorPinResetView,
    OperatorSessionView,
    OperatorUnlockView,
    OrderAdvanceView,
    OrderAssignView,
    OrderCancellationReasonsView,
    OrderCancelView,
    OrderCommentView,
    OrderConfirmView,
    OrderCourierCancelView,
    OrderCourierDispatchView,
    OrderCourierQuoteView,
    OrderDetailView,
    OrderNotesView,
    OrderQueueView,
    OrderRejectView,
    OrderRequeueFiscalView,
    OrderSettleDeliveryCashView,
    OrderUnassignView,
    POSCancelRecentSaleView,
    POSCashCloseBlockingView,
    POSCashCloseView,
    POSCashMovementView,
    POSCashOpenView,
    POSCloseSaleView,
    POSCustomerLookupView,
    POSCustomerResolveView,
    POSCustomerSearchView,
    POSPaymentStatusView,
    POSReviewSaleView,
    POSTabClearView,
    POSTabCreateView,
    POSTabFireView,
    POSTabMoveLinesView,
    POSTabOpenView,
    POSTabRenameView,
    POSTabSaveView,
    POSTabUnfireView,
    POSView,
    ProductionBoardView,
    ProductionForecastView,
    ProductionKDSView,
    ProductionMiseEnPlaceView,
    ProductionWeighingView,
    WorkOrderAdvanceStepView,
    WorkOrderFinishView,
    WorkOrderPlanView,
    WorkOrderQuickFinishView,
    WorkOrderStartView,
    WorkOrderVoidView,
)
from .showcase import (
    ShowcaseActiveView,
    ShowcaseBoardView,
    ShowcaseCollectionsView,
)
from .telemetry import ClientErrorView

urlpatterns = [
    # Telemetria — erro de cliente das superfícies de operador (operator-kit)
    path("client-error/", ClientErrorView.as_view(), name="api-backstage-client-error"),
    # Central de Apps — launcher do operador (surfaces/hub-nuxt)
    path("hub/", HubView.as_view(), name="api-backstage-hub"),
    # KDS
    path("kds/", KDSIndexView.as_view(), name="api-backstage-kds-index"),
    path("kds/cliente/", KDSCustomerStatusView.as_view(), name="api-backstage-kds-customer"),
    path("kds/<slug:ref>/", KDSBoardView.as_view(), name="api-backstage-kds-board"),
    path("kds/tickets/<int:ticket_pk>/items/", KDSTicketItemView.as_view(), name="api-backstage-kds-ticket-item"),
    path("kds/tickets/<int:ticket_pk>/done/", KDSTicketDoneView.as_view(), name="api-backstage-kds-ticket-done"),
    path("kds/tickets/<int:ticket_pk>/recall/", KDSTicketRecallView.as_view(), name="api-backstage-kds-ticket-recall"),
    path("kds/tickets/<int:ticket_pk>/acknowledge/", KDSTicketAcknowledgeView.as_view(), name="api-backstage-kds-ticket-acknowledge"),
    path("kds/expedition/<int:order_pk>/action/", KDSExpeditionActionView.as_view(), name="api-backstage-kds-expedition"),
    # Operations — read views
    path("pos/", POSView.as_view(), name="api-backstage-pos"),
    # Operador (PIN/crachá) — genérico, compartilhado por todas as surfaces (inclui POS)
    path("operator/login/", OperatorLoginView.as_view(), name="api-backstage-operator-login"),
    path("operator/session/", OperatorSessionView.as_view(), name="api-backstage-operator-session"),
    path("operator/eligible/", OperatorEligibleView.as_view(), name="api-backstage-operator-eligible"),
    path("operator/unlock/", OperatorUnlockView.as_view(), name="api-backstage-operator-unlock"),
    path("operator/lock/", OperatorLockView.as_view(), name="api-backstage-operator-lock"),
    path("operator/pin/change/", OperatorPinChangeView.as_view(), name="api-backstage-operator-pin-change"),
    path("operator/pin/reset/", OperatorPinResetView.as_view(), name="api-backstage-operator-pin-reset"),
    path("production/", ProductionBoardView.as_view(), name="api-backstage-production"),
    path("production/kds/", ProductionKDSView.as_view(), name="api-backstage-production-kds"),
    path("production/forecast/", ProductionForecastView.as_view(), name="api-backstage-production-forecast"),
    path(
        "production/mise-en-place/",
        ProductionMiseEnPlaceView.as_view(),
        name="api-backstage-production-mise-en-place",
    ),
    path(
        "production/weighing/",
        ProductionWeighingView.as_view(),
        name="api-backstage-production-weighing",
    ),
    path("closing/", DayClosingView.as_view(), name="api-backstage-closing"),
    path("orders/", OrderQueueView.as_view(), name="api-backstage-orders"),
    # Catalog matrix (produto × superfície)
    path("catalog/", CatalogMatrixView.as_view(), name="api-backstage-catalog"),
    path("catalog/cell/", CatalogCellView.as_view(), name="api-backstage-catalog-cell"),
    path("catalog/product/", CatalogProductView.as_view(), name="api-backstage-catalog-product"),
    path("catalog/product/<str:sku>/", CatalogProductDetailView.as_view(), name="api-backstage-catalog-product-detail"),
    path("catalog/bulk/", CatalogBulkView.as_view(), name="api-backstage-catalog-bulk"),
    path("catalog/bulk-price/", CatalogBulkPriceView.as_view(), name="api-backstage-catalog-bulk-price"),
    path("catalog/reorder-collections/", CatalogReorderCollectionsView.as_view(), name="api-backstage-catalog-reorder-collections"),
    path("catalog/reorder-items/", CatalogReorderItemsView.as_view(), name="api-backstage-catalog-reorder-items"),
    path("catalog/sync-status/", CatalogSyncStatusView.as_view(), name="api-backstage-catalog-sync-status"),
    path("catalog/resync/", CatalogResyncView.as_view(), name="api-backstage-catalog-resync"),
    path("catalog/social/", CatalogSocialView.as_view(), name="api-backstage-catalog-social"),
    # Expositores (display: menuboard/feeds)
    path("showcases/", ShowcaseBoardView.as_view(), name="api-backstage-showcases"),
    path("showcases/active/", ShowcaseActiveView.as_view(), name="api-backstage-showcases-active"),
    path("showcases/collections/", ShowcaseCollectionsView.as_view(), name="api-backstage-showcases-collections"),
    # Orders — operator actions
    path("orders/<str:ref>/", OrderDetailView.as_view(), name="api-backstage-order-detail"),
    path("orders/<str:ref>/advance/", OrderAdvanceView.as_view(), name="api-backstage-order-advance"),
    path("orders/<str:ref>/confirm/", OrderConfirmView.as_view(), name="api-backstage-order-confirm"),
    path("orders/<str:ref>/reject/", OrderRejectView.as_view(), name="api-backstage-order-reject"),
    path("orders/<str:ref>/cancel/", OrderCancelView.as_view(), name="api-backstage-order-cancel"),
    path("orders/<str:ref>/cancellation-reasons/", OrderCancellationReasonsView.as_view(), name="api-backstage-order-cancellation-reasons"),
    path("orders/<str:ref>/settle-delivery-cash/", OrderSettleDeliveryCashView.as_view(), name="api-backstage-order-settle-delivery-cash"),
    path("orders/<str:ref>/requeue-fiscal/", OrderRequeueFiscalView.as_view(), name="api-backstage-order-requeue-fiscal"),
    path("orders/<str:ref>/notes/", OrderNotesView.as_view(), name="api-backstage-order-notes"),
    path("orders/<str:ref>/courier-dispatch/", OrderCourierDispatchView.as_view(), name="api-backstage-order-courier-dispatch"),
    path("orders/<str:ref>/courier-cancel/", OrderCourierCancelView.as_view(), name="api-backstage-order-courier-cancel"),
    path("orders/<str:ref>/courier-quote/", OrderCourierQuoteView.as_view(), name="api-backstage-order-courier-quote"),
    path("orders/<str:ref>/assign/", OrderAssignView.as_view(), name="api-backstage-order-assign"),
    path("orders/<str:ref>/unassign/", OrderUnassignView.as_view(), name="api-backstage-order-unassign"),
    path("orders/<str:ref>/comment/", OrderCommentView.as_view(), name="api-backstage-order-comment"),
    # Operator alerts
    path("alerts/", AlertListView.as_view(), name="api-backstage-alerts"),
    path("alerts/<int:pk>/ack/", AlertAckView.as_view(), name="api-backstage-alert-ack"),
    # Production — work order actions
    path("production/plan/", WorkOrderPlanView.as_view(), name="api-backstage-wo-plan"),
    path("production/<int:wo_id>/start/", WorkOrderStartView.as_view(), name="api-backstage-wo-start"),
    path("production/<int:wo_id>/finish/", WorkOrderFinishView.as_view(), name="api-backstage-wo-finish"),
    path("production/<int:wo_id>/advance-step/", WorkOrderAdvanceStepView.as_view(), name="api-backstage-wo-advance"),
    path("production/quick-finish/", WorkOrderQuickFinishView.as_view(), name="api-backstage-wo-quick-finish"),
    path("production/<int:wo_id>/void/", WorkOrderVoidView.as_view(), name="api-backstage-wo-void"),
    # POS — cash session actions
    path("pos/cash/open/", POSCashOpenView.as_view(), name="api-backstage-pos-cash-open"),
    path("pos/cash/close/", POSCashCloseView.as_view(), name="api-backstage-pos-cash-close"),
    path("pos/cash/close-blocking/", POSCashCloseBlockingView.as_view(), name="api-backstage-pos-cash-close-blocking"),
    path("pos/cash/movement/", POSCashMovementView.as_view(), name="api-backstage-pos-cash-movement"),
    # POS — tab (comanda) lifecycle
    path("pos/tabs/", POSTabCreateView.as_view(), name="api-backstage-pos-tab-create"),
    path("pos/tabs/<str:tab_ref>/open/", POSTabOpenView.as_view(), name="api-backstage-pos-tab-open"),
    path("pos/tabs/save/", POSTabSaveView.as_view(), name="api-backstage-pos-tab-save"),
    path("pos/tabs/rename/", POSTabRenameView.as_view(), name="api-backstage-pos-tab-rename"),
    path("pos/tabs/move-lines/", POSTabMoveLinesView.as_view(), name="api-backstage-pos-tab-move-lines"),
    path("pos/tabs/fire/", POSTabFireView.as_view(), name="api-backstage-pos-tab-fire"),
    path("pos/tabs/unfire/", POSTabUnfireView.as_view(), name="api-backstage-pos-tab-unfire"),
    path("pos/tabs/<str:session_key>/clear/", POSTabClearView.as_view(), name="api-backstage-pos-tab-clear"),
    path("pos/sale/review/", POSReviewSaleView.as_view(), name="api-backstage-pos-review-sale"),
    path("pos/sale/close/", POSCloseSaleView.as_view(), name="api-backstage-pos-close-sale"),
    path("pos/sale/recent/cancel/", POSCancelRecentSaleView.as_view(), name="api-backstage-pos-cancel-recent-sale"),
    path("pos/payment/<str:ref>/status/", POSPaymentStatusView.as_view(), name="api-backstage-pos-payment-status"),
    path("pos/customer/lookup/", POSCustomerLookupView.as_view(), name="api-backstage-pos-customer-lookup"),
    path("pos/customer/search/", POSCustomerSearchView.as_view(), name="api-backstage-pos-customer-search"),
    path("pos/customer/resolve/", POSCustomerResolveView.as_view(), name="api-backstage-pos-customer-resolve"),
]
