# Generated by Django 5.2.12 on 2026-04-02 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shopman.models.shop


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerman', '0002_rename_offering_pro_is_publ_idx_offering_pr_is_publ_6ea7fc_idx_and_more'),
        ('omniman', '0005_session_origin_channel_order_origin_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.SlugField(help_text='Identificador do evento (ex: order_confirmed, payment_refunded)', unique=True, verbose_name='evento')),
                ('subject', models.CharField(help_text='Assunto do email. Suporta {placeholders}.', max_length=200, verbose_name='assunto')),
                ('body', models.TextField(help_text='Texto principal da notificação (WhatsApp-first). Suporta {placeholders}.', verbose_name='mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'template de notificação',
                'verbose_name_plural': 'templates de notificação',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo')], max_length=30, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('order_ref', models.CharField(blank=True, max_length=50, verbose_name='ref do pedido')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='reconhecido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'alerta operacional',
                'verbose_name_plural': 'alertas operacionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], max_length=10, verbose_name='tipo')),
                ('value', models.IntegerField(help_text='Percentual (0-100) ou valor fixo em centavos', verbose_name='valor')),
                ('valid_from', models.DateTimeField(verbose_name='válido de')),
                ('valid_until', models.DateTimeField(verbose_name='válido até')),
                ('skus', models.JSONField(blank=True, default=list, help_text='SKUs afetados (vazio = todos). Ex: ["PAO-FRANCES", "CROISSANT"]', verbose_name='SKUs')),
                ('collections', models.JSONField(blank=True, default=list, help_text='Collection refs afetados (vazio = todos). Ex: ["paes-artesanais", "confeitaria"]', verbose_name='coleções')),
                ('min_order_q', models.IntegerField(default=0, help_text='Valor mínimo do pedido em centavos (0 = sem mínimo)', verbose_name='pedido mínimo (centavos)')),
                ('fulfillment_types', models.JSONField(blank=True, default=list, help_text='Tipos de entrega (vazio = todos). Ex: ["delivery", "pickup"]', verbose_name='tipos de entrega')),
                ('customer_segments', models.JSONField(blank=True, default=list, help_text='Segmentos RFM para targeting (vazio = todos). Ex: ["champions", "loyal"]', verbose_name='segmentos de cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='razão social')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('formatted_address', models.CharField(blank=True, help_text='Endereço formatado completo (ex: Av. Madre Leônia Milito, 446 - Bela Suíça, Londrina - PR, 86050-270)', max_length=500, verbose_name='endereço completo')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state_code', models.CharField(blank=True, max_length=5, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='país')),
                ('country_code', models.CharField(default='BR', max_length=5, verbose_name='código do país')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('place_id', models.CharField(blank=True, max_length=255, verbose_name='Google Place ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('default_ddd', models.CharField(default='11', max_length=4, verbose_name='DDD padrão')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='fuso horário')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Horários por dia da semana. Exemplo: {"monday": {"open": "06:00", "close": "20:00"}, "tuesday": {"open": "06:00", "close": "20:00"}, ...}. Dias: monday, tuesday, wednesday, thursday, friday, saturday, sunday.', verbose_name='horários')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='nome curto (PWA)')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='tagline')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('primary_color', models.CharField(default='#9E833E', max_length=9, verbose_name='cor primária')),
                ('logo', models.FileField(blank=True, help_text='SVG, PNG, JPG ou WebP. Máximo 2MB. Exibido com altura de 40px no header.', upload_to='branding/', validators=[shopman.models.shop.validate_logo], verbose_name='logotipo')),
                ('secondary_color', models.CharField(blank=True, default='', help_text='Cor de apoio. Vazio = derivada automaticamente (hue +120° da primária)', max_length=9, verbose_name='cor secundária')),
                ('accent_color', models.CharField(blank=True, default='', help_text='Cor de destaque/CTA. Vazio = derivada automaticamente (hue -60° da primária)', max_length=9, verbose_name='cor de destaque')),
                ('neutral_color', models.CharField(blank=True, default='', help_text='Fundo da página no modo claro. Superfícies clareiam para branco. Vazio = creme derivado da primária.', max_length=9, verbose_name='tom neutro (claro)')),
                ('neutral_dark_color', models.CharField(blank=True, default='', help_text='Fundo da página no modo escuro. Superfícies escurecem para preto. Vazio = derivado do tom claro.', max_length=9, verbose_name='tom neutro (escuro)')),
                ('color_mode', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático (sistema do usuário)')], default='light', help_text='Automático respeita a preferência de tema do sistema do usuário', max_length=10, verbose_name='modo de cor')),
                ('heading_font', models.CharField(choices=[('Playfair Display', 'Playfair Display'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('EB Garamond', 'EB Garamond'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Serif Display', 'DM Serif Display'), ('Fraunces', 'Fraunces'), ('Bitter', 'Bitter'), ('Crimson Pro', 'Crimson Pro')], default='Playfair Display', max_length=100, verbose_name='fonte de títulos')),
                ('body_font', models.CharField(choices=[('Inter', 'Inter'), ('DM Sans', 'DM Sans'), ('Work Sans', 'Work Sans'), ('Plus Jakarta Sans', 'Plus Jakarta Sans'), ('Nunito Sans', 'Nunito Sans'), ('Source Sans 3', 'Source Sans 3'), ('Outfit', 'Outfit'), ('Raleway', 'Raleway'), ('Rubik', 'Rubik'), ('Manrope', 'Manrope')], default='Inter', max_length=100, verbose_name='fonte de corpo')),
                ('border_radius', models.CharField(choices=[('square', 'Quadrado (0px)'), ('soft', 'Suave (4px)'), ('default', 'Padrão (8px)'), ('strong', 'Forte (16px)'), ('round', 'Redondo (9999px)')], default='default', help_text='Define o arredondamento dos cantos de botões, cards e inputs', max_length=20, verbose_name='arredondamento')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='Lista de URLs das redes sociais. Exemplo:\n[\n  "https://wa.me/554333231997",\n  "https://instagram.com/nelsonboulangerie",\n  "https://www.facebook.com/nelsonboulangerie",\n  "https://www.tiktok.com/@nelsonboulangerie",\n  "https://www.youtube.com/@nelsonboulangerie",\n  "https://twitter.com/nelsonboulangerie",\n  "https://www.nelsonboulangerie.com.br"\n]\nPlataformas reconhecidas: WhatsApp, Instagram, Facebook, TikTok, YouTube, X/Twitter, LinkedIn, Telegram, Pinterest. Qualquer outra URL aparece como ícone de link genérico.', verbose_name='redes sociais')),
                ('tracking_copy', models.JSONField(blank=True, default=dict, help_text='Mensagens exibidas ao cliente na página de acompanhamento do pedido.\nDeixe vazio para usar os textos padrão. Preencha apenas as que quiser personalizar.\n\nChaves disponíveis:\n  "new" — pedido recebido, aguardando confirmação\n  "new_countdown" — texto acima do timer de confirmação\n  "confirmed" — pedido confirmado\n  "processing" — pedido em preparo\n  "ready" — pedido pronto para retirada/entrega\n  "dispatched" — pedido saiu para entrega\n  "delivered" — pedido entregue\n  "completed" — pedido concluído\n  "cancelled" — pedido cancelado\n  "confirmed_celebration" — texto ao confirmar (timer zerou)\n', verbose_name='textos do acompanhamento')),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Mesmo schema do ChannelConfig. Canais herdam se não sobreescreverem.', verbose_name='configurações padrão')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'loja',
            },
        ),
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('data', models.JSONField(blank=True, default=list, help_text='Lista de dicts: [{sku, qty_remaining, qty_d1, qty_loss}]', verbose_name='snapshot')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento do dia',
                'verbose_name_plural': 'fechamentos do dia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('prep', 'Preparo'), ('picking', 'Separação'), ('expedition', 'Expedição')], max_length=20, verbose_name='tipo')),
                ('target_time_minutes', models.PositiveIntegerField(default=10, help_text='Timer fica amarelo após este tempo, vermelho após 2x.', verbose_name='tempo alvo (min)')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='som ativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('config', models.JSONField(blank=True, default=dict, help_text='text_size, dark_mode, refresh_interval, etc.', verbose_name='configurações')),
                ('collections', models.ManyToManyField(blank=True, help_text='Categorias de produto que esta estação processa. Vazio = catch-all.', to='offerman.collection', verbose_name='coleções')),
            ],
            options={
                'verbose_name': 'instância KDS',
                'verbose_name_plural': 'instâncias KDS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='[{"sku", "name", "qty", "notes", "checked": false}]', verbose_name='items')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluído')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('kds_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shopman.kdsinstance', verbose_name='estação KDS')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'ticket KDS',
                'verbose_name_plural': 'tickets KDS',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='código')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='usos máximos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shopman.promotion', verbose_name='promoção')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='código')),
                ('rule_path', models.CharField(help_text='Dotted path to the rule class (e.g. shopman.rules.pricing.D1Rule)', max_length=200, verbose_name='caminho da regra')),
                ('label', models.CharField(max_length=120, verbose_name='nome exibido')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Parâmetros da regra (ex: percentual, horários, SKUs)', verbose_name='parâmetros')),
                ('priority', models.IntegerField(default=0, help_text='Regras com menor número são avaliadas primeiro', verbose_name='prioridade')),
                ('channels', models.ManyToManyField(blank=True, help_text='Canais onde esta regra se aplica. Vazio = todos.', to='omniman.channel', verbose_name='canais')),
            ],
            options={
                'verbose_name': 'regra configurável',
                'verbose_name_plural': 'regras configuráveis',
                'ordering': ['priority'],
            },
        ),
    ]
