# Generated by Django 5.2.12 on 2026-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='border_radius',
            field=models.CharField(choices=[('square', 'Quadrado (0px)'), ('soft', 'Suave (8px)'), ('default', 'Padrão (12px)'), ('strong', 'Forte (24px)'), ('round', 'Redondo (9999px)')], default='default', help_text='Define o arredondamento dos cantos de botões, cards e inputs', max_length=20, verbose_name='arredondamento'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='heading_font',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Playfair Display', 'Playfair Display'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('EB Garamond', 'EB Garamond'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Serif Display', 'DM Serif Display'), ('Fraunces', 'Fraunces'), ('Bitter', 'Bitter'), ('Crimson Pro', 'Crimson Pro')], default='Inter', max_length=100, verbose_name='fonte de títulos'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='primary_color',
            field=models.CharField(default='#2563EB', max_length=9, verbose_name='cor primária'),
        ),
    ]
