# Generated by Django 5.2.12 on 2026-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0002_alter_shop_border_radius_alter_shop_heading_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='primary_color',
            field=models.CharField(default='#1a1a1a', max_length=9, verbose_name='cor primária'),
        ),
    ]
