# Generated by Django 5.2.12 on 2026-04-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0003_alter_shop_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('zone_type', models.CharField(choices=[('cep_prefix', 'Prefixo de CEP'), ('neighborhood', 'Bairro')], default='cep_prefix', max_length=20, verbose_name='tipo de zona')),
                ('match_value', models.CharField(help_text="Para 'Prefixo de CEP': dígitos iniciais sem hífen (ex: '860' cobre 860xx-xxx). Para 'Bairro': nome exato do bairro (comparação sem maiúsculas/minúsculas). ", max_length=100, verbose_name='valor de correspondência')),
                ('fee_q', models.PositiveIntegerField(default=0, help_text='Taxa em centavos. 0 = entrega grátis.', verbose_name='taxa de entrega (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Menor número = maior prioridade dentro do mesmo tipo.', verbose_name='ordem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='shopman.shop', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'zona de entrega',
                'verbose_name_plural': 'zonas de entrega',
                'ordering': ['zone_type', 'sort_order', 'name'],
            },
        ),
    ]
