# Generated by Django 5.2.12 on 2026-04-06 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0004_deliveryzone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_amount_q', models.IntegerField(default=0, help_text='Valor de abertura em centavos (fundo de troco).')),
                ('closing_amount_q', models.IntegerField(blank=True, help_text='Valor informado no fechamento em centavos.', null=True)),
                ('expected_amount_q', models.IntegerField(blank=True, help_text='Calculado: abertura + vendas_dinheiro + suprimentos - sangrias.', null=True)),
                ('difference_q', models.IntegerField(blank=True, help_text='Diferença: fechamento informado - esperado (positivo = sobra).', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('amount_q', models.IntegerField(help_text='Valor em centavos (sempre positivo).')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='shopman.cashregistersession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-created_at'],
            },
        ),
    ]
