# Generated by Django 5.2.12 on 2026-04-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0005_cash_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível')], max_length=50, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tracking_copy',
            field=models.JSONField(blank=True, default=dict, help_text='Mensagens exibidas ao cliente na página de acompanhamento do pedido.\nDeixe vazio para usar os textos padrão. Preencha apenas as que quiser personalizar.\n\nChaves disponíveis:\n  "new" — pedido recebido, aguardando confirmação\n  "new_countdown" — texto acima do timer de confirmação\n  "confirmed" — pedido confirmado\n  "preparing" — pedido em preparo\n  "ready" — pedido pronto para retirada/entrega\n  "dispatched" — pedido saiu para entrega\n  "delivered" — pedido entregue\n  "completed" — pedido concluído\n  "cancelled" — pedido cancelado\n  "confirmed_celebration" — texto ao confirmar (timer zerou)\n', verbose_name='textos do acompanhamento'),
        ),
    ]
