# Generated by Django 5.2.12 on 2026-04-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopman', '0006_sync_alert_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfigRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_ref', models.CharField(help_text='Ref do canal (deve corresponder a Channel.ref no Omniman).', max_length=64, unique=True, verbose_name='ref do canal')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Override de ChannelConfig para este canal. Mesmo schema do ChannelConfig.to_dict(). Apenas as chaves presentes sobrescrevem os defaults da loja.', verbose_name='configuração')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'config de canal',
                'verbose_name_plural': 'configs de canais',
                'ordering': ['channel_ref'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='integrations',
            field=models.JSONField(blank=True, default=dict, help_text='Seleção de adapters por tipo. Sobreescreve settings.py. Mesmo schema que SHOPMAN_*_ADAPTERS.\n\nExemplo:\n{\n  "payment": {"pix": "shopman.adapters.payment_efi", "card": "shopman.adapters.payment_stripe"},\n  "notification": {"default": "shopman.adapters.notification_manychat"},\n  "fiscal": "shopman.adapters.fiscal_nfce"\n}', verbose_name='integrações'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs das redes sociais. Exemplo:\n[\n  "https://wa.me/5511999999999",\n  "https://instagram.com/example",\n  "https://www.facebook.com/example",\n  "https://www.tiktok.com/@example",\n  "https://www.youtube.com/@example",\n  "https://twitter.com/example",\n  "https://www.example.com.br"\n]\nPlataformas reconhecidas: WhatsApp, Instagram, Facebook, TikTok, YouTube, X/Twitter, LinkedIn, Telegram, Pinterest. Qualquer outra URL aparece como ícone de link genérico.', verbose_name='redes sociais'),
        ),
    ]
